<?php

namespace Club\MessageBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MessageQueue
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageQueue extends EntityRepository
{
  public function getQueued($limit=100)
  {
    return $this->_em->createQueryBuilder()
      ->select('mq')
      ->from('ClubMessageBundle:MessageQueue','mq')
      ->leftJoin('mq.message','m')
      ->where('m.type=:type')
      ->andWhere('mq.processed=0')
      ->setMaxResults($limit)
      ->setParameter('type','mail')
      ->getQuery()
      ->getResult();
  }
}
