<?php

namespace Club\MessageBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MessageAttachmetn
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageAttachment extends EntityRepository
{
}
