<?php

namespace Club\MessageBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Message
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Message extends EntityRepository
{
}
