<?php

namespace Club\AccountBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Account
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Account extends EntityRepository
{
}
