<?php

namespace Club\AccountBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Ledger
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Ledger extends EntityRepository
{
}
