<?php

namespace Club\RequestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RequestCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequestCommentRepository extends EntityRepository
{
}