<?php

namespace Club\RequestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequestRepository extends EntityRepository
{
  public function getOpen()
  {
    return $this->_em->createQueryBuilder()
      ->select('r')
      ->from('ClubRequestBundle:Request', 'r')
      ->where('r.play_time > :date')
      ->andWhere('r.closed = false')
      ->orderBy('r.play_time')
      ->setParameter('date', new \DateTime())
      ->getQuery()
      ->getResult();
  }
}
