<?php

namespace Club\RankingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatchRepository extends EntityRepository
{
    public function getUnprocessed()
    {
        return $this->createQueryBuilder('m')
            ->where('m.processed = false')
            ->getQuery()
            ->getResult();
    }
}
