<?php

namespace Club\RankingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RankingTableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RankingTableRepository extends EntityRepository
{
  public function getTeam(\Club\RankingBundle\Entity\Ranking $ranking, \Club\MatchBundle\Entity\Team $team)
  {
    $lt = $this->_em->getRepository('ClubRankingBundle:RankingTable')->findOneBy(array(
      'ranking' => $ranking->getId(),
      'team' => $team->getId()
    ));

    if (!$lt)
      $lt = $this->addTeam($ranking, $team);

    return $lt;
  }

  public function addTeam(\Club\RankingBundle\Entity\Ranking $ranking, \Club\MatchBundle\Entity\Team $team)
  {
    $lt = new \Club\RankingBundle\Entity\RankingTable();
    $lt->setRanking($ranking);
    $lt->setTeam($team);

    $this->_em->persist($lt);

    return $lt;
  }
}
