<?php

namespace Club\CheckinBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CheckinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CheckinRepository extends EntityRepository
{
}