<?php

namespace Club\TeamBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ParticipantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipantRepository extends EntityRepository
{
  public function getUserInRange(\Club\UserBundle\Entity\User $user, \DateTime $first, \DateTime $last)
  {
    return $this->_em->createQueryBuilder()
      ->select('p')
      ->from('ClubTeamBundle:Participant', 'p')
      ->where('p.user = :user')
      ->andWhere('p.created_at >= :first')
      ->andWhere('p.created_at <= :last')
      ->setParameter('user', $user->getId())
      ->setParameter('first', $first)
      ->setParameter('last', $last)
      ->getQuery()
      ->getResult();
  }
}
