<?php

namespace Club\NewsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnnouncementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnouncementRepository extends EntityRepository
{
    public function getOpen()
    {
        return $this->createQueryBuilder('a')
            ->where('a.start_date < :date')
            ->andWhere('a.end_date > :date')
            ->setParameter('date', new \DateTime())
            ->getQuery()
            ->getResult();
    }
}
