<?php

namespace Club\NewsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TickerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TickerRepository extends EntityRepository
{
    public function getOpen()
    {
        return $this->createQueryBuilder('t')
            ->where('t.start_date < :date')
            ->andWhere('t.end_date > :date')
            ->setParameter('date', new \DateTime())
            ->getQuery()
            ->getResult();
    }
}
