<?php

namespace Club\NewsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TickerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TickerRepository extends EntityRepository
{
}