<?php

namespace Club\MatchBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LeagueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeagueRepository extends EntityRepository
{
  public function getTopLists($limit=10)
  {
    $games = $this->_em->getRepository('ClubMatchBundle:League', 'l')->findAll();

    foreach ($games as $league) {
      $matches = $this->_em->createQueryBuilder()
        ->select('m')
        ->from('ClubMatchBundle:Match', 'm')
        ->where('m.league = :league')
        ->orderBy('m.id', 'DESC')
        ->setMaxResults($limit)
        ->setParameter('league', $league->getId())
        ->getQuery()
        ->getResult();

      $league->setMatches($matches);
    }

    return $games;
  }
}
