<?php

namespace Club\MatchBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LeagueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeagueRepository extends EntityRepository
{
  public function getRecentMatches(\Club\MatchBundle\Entity\League $league, $limit=10)
  {
    $matches = $this->_em->createQueryBuilder()
      ->select('m')
      ->from('ClubMatchBundle:Match', 'm')
      ->where('m.league = :league')
      ->orderBy('m.id', 'DESC')
      ->setMaxResults($limit)
      ->setParameter('league', $league->getId())
      ->getQuery()
      ->getResult();

    return $matches;
  }

  public function getTop(\Club\MatchBundle\Entity\League $league, $limit=4)
  {
    $rank = $this->_em->createQueryBuilder()
      ->select('lt')
      ->from('ClubMatchBundle:LeagueTable', 'lt')
      ->where('lt.league = :league')
      ->orderBy('lt.point', 'DESC')
      ->setMaxResults($limit)
      ->setParameter('league', $league->getId())
      ->getQuery()
      ->getResult();

    return $rank;
  }
}
