<?php

namespace Club\MatchBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatchRepository extends EntityRepository
{
  public function getUnprocessed()
  {
    return $this->_em->createQueryBuilder()
      ->select('m')
      ->from('ClubMatchBundle:Match', 'm')
      ->where('m.processed = false')
      ->getQuery()
      ->getResult();
  }
}
