<?php

namespace Club\MatchBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatchRepository extends EntityRepository
{
  public function getUnprocessed()
  {
    return $this->_em->createQueryBuilder()
      ->select('m')
      ->from('ClubMatchBundle:Match', 'm')
      ->where('m.processed = false')
      ->getQuery()
      ->getResult();
  }

  public function getRecentMatches(\Club\MatchBundle\Entity\League $league=null, $limit=10)
  {
    $qb = $this->_em->createQueryBuilder()
      ->select('m')
      ->from('ClubMatchBundle:Match', 'm')
      ->orderBy('m.id', 'DESC')
      ->setMaxResults($limit);

    if ($league) {
      $qb->where('m.league = :league')
      ->setParameter('league', $league->getId());
    }

    return $qb
      ->getQuery()
      ->getResult();
  }
}
