CREATE TABLE club_user_connection (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, connection_id INT DEFAULT NULL, type VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, INDEX IDX_91868754A76ED395 (user_id), INDEX IDX_91868754DD03F01 (connection_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE club_exchange_exchange_comment (id INT AUTO_INCREMENT NOT NULL, exchange_id INT DEFAULT NULL, user_id INT DEFAULT NULL, comment LONGTEXT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_728F964E68AFD1A0 (exchange_id), INDEX IDX_728F964EA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE club_exchange_exchange (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, location_id INT DEFAULT NULL, play_time DATETIME NOT NULL, message LONGTEXT NOT NULL, closed TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_9EAF6F1EA76ED395 (user_id), INDEX IDX_9EAF6F1E64D218E (location_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE club_tournament_tournament_attend (id INT AUTO_INCREMENT NOT NULL, tournament_id INT DEFAULT NULL, user_id INT DEFAULT NULL, seed INT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_6990BDF633D1A3E7 (tournament_id), INDEX IDX_6990BDF6A76ED395 (user_id), UNIQUE INDEX uniq_idx (tournament_id, user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE club_tournament_tournament (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, game_set INT NOT NULL, min_attend INT NOT NULL, max_attend INT DEFAULT NULL, seeds INT DEFAULT NULL, build TINYINT(1) NOT NULL, rounds INT DEFAULT NULL, start_time DATETIME NOT NULL, description LONGTEXT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE club_tournament_tournament_game (id INT AUTO_INCREMENT NOT NULL, tournament_id INT DEFAULT NULL, tournament_round_id INT DEFAULT NULL, team_one_id INT DEFAULT NULL, team_two_id INT DEFAULT NULL, winner_id INT DEFAULT NULL, game INT NOT NULL, result VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_B7C58C1433D1A3E7 (tournament_id), INDEX IDX_B7C58C1446BEBA45 (tournament_round_id), INDEX IDX_B7C58C148D8189CA (team_one_id), INDEX IDX_B7C58C14E6DD6E05 (team_two_id), INDEX IDX_B7C58C145DFCD4B8 (winner_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE club_tournament_tournament_round (id INT AUTO_INCREMENT NOT NULL, tournament_id INT DEFAULT NULL, round INT NOT NULL, round_name VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_3BAE1FFF33D1A3E7 (tournament_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE club_news_ticker (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, message LONGTEXT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_2C989369A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE club_ranking_match (id INT AUTO_INCREMENT NOT NULL, ranking_id INT DEFAULT NULL, match_id INT DEFAULT NULL, processed TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_CA58D40020F64684 (ranking_id), INDEX IDX_CA58D4002ABEACD6 (match_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE club_ranking_ranking_entry (id INT AUTO_INCREMENT NOT NULL, ranking_id INT DEFAULT NULL, team_id INT DEFAULT NULL, played INT NOT NULL, won INT NOT NULL, lost INT NOT NULL, point INT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_39FF296520F64684 (ranking_id), INDEX IDX_39FF2965296CD8AE (team_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE club_ranking_ranking (id INT AUTO_INCREMENT NOT NULL, rule_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, gender VARCHAR(255) DEFAULT NULL, invite_only TINYINT(1) NOT NULL, game_set INT NOT NULL, type VARCHAR(255) NOT NULL, start_date DATETIME NOT NULL, end_date DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_977F5D64744E0351 (rule_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE club_ranking_users (ranking_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_A480B4EC20F64684 (ranking_id), INDEX IDX_A480B4ECA76ED395 (user_id), PRIMARY KEY(ranking_id, user_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE club_ranking_rule (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, point_won INT NOT NULL, point_lost INT NOT NULL, same_player INT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE club_user_connection ADD CONSTRAINT FK_91868754A76ED395 FOREIGN KEY (user_id) REFERENCES club_user_user (id);
ALTER TABLE club_user_connection ADD CONSTRAINT FK_91868754DD03F01 FOREIGN KEY (connection_id) REFERENCES club_user_user (id);
ALTER TABLE club_exchange_exchange_comment ADD CONSTRAINT FK_728F964E68AFD1A0 FOREIGN KEY (exchange_id) REFERENCES club_exchange_exchange (id) ON DELETE CASCADE;
ALTER TABLE club_exchange_exchange_comment ADD CONSTRAINT FK_728F964EA76ED395 FOREIGN KEY (user_id) REFERENCES club_user_user (id);
ALTER TABLE club_exchange_exchange ADD CONSTRAINT FK_9EAF6F1EA76ED395 FOREIGN KEY (user_id) REFERENCES club_user_user (id);
ALTER TABLE club_exchange_exchange ADD CONSTRAINT FK_9EAF6F1E64D218E FOREIGN KEY (location_id) REFERENCES club_user_location (id);
ALTER TABLE club_tournament_tournament_attend ADD CONSTRAINT FK_6990BDF633D1A3E7 FOREIGN KEY (tournament_id) REFERENCES club_tournament_tournament (id);
ALTER TABLE club_tournament_tournament_attend ADD CONSTRAINT FK_6990BDF6A76ED395 FOREIGN KEY (user_id) REFERENCES club_user_user (id);
ALTER TABLE club_tournament_tournament_game ADD CONSTRAINT FK_B7C58C1433D1A3E7 FOREIGN KEY (tournament_id) REFERENCES club_tournament_tournament (id);
ALTER TABLE club_tournament_tournament_game ADD CONSTRAINT FK_B7C58C1446BEBA45 FOREIGN KEY (tournament_round_id) REFERENCES club_tournament_tournament_round (id);
ALTER TABLE club_tournament_tournament_game ADD CONSTRAINT FK_B7C58C148D8189CA FOREIGN KEY (team_one_id) REFERENCES club_user_user (id);
ALTER TABLE club_tournament_tournament_game ADD CONSTRAINT FK_B7C58C14E6DD6E05 FOREIGN KEY (team_two_id) REFERENCES club_user_user (id);
ALTER TABLE club_tournament_tournament_game ADD CONSTRAINT FK_B7C58C145DFCD4B8 FOREIGN KEY (winner_id) REFERENCES club_user_user (id);
ALTER TABLE club_tournament_tournament_round ADD CONSTRAINT FK_3BAE1FFF33D1A3E7 FOREIGN KEY (tournament_id) REFERENCES club_tournament_tournament (id);
ALTER TABLE club_news_ticker ADD CONSTRAINT FK_2C989369A76ED395 FOREIGN KEY (user_id) REFERENCES club_user_user (id);
ALTER TABLE club_ranking_match ADD CONSTRAINT FK_CA58D40020F64684 FOREIGN KEY (ranking_id) REFERENCES club_ranking_ranking (id);
ALTER TABLE club_ranking_match ADD CONSTRAINT FK_CA58D4002ABEACD6 FOREIGN KEY (match_id) REFERENCES club_match_match (id) ON DELETE CASCADE;
ALTER TABLE club_ranking_ranking_entry ADD CONSTRAINT FK_39FF296520F64684 FOREIGN KEY (ranking_id) REFERENCES club_ranking_ranking (id) ON DELETE CASCADE;
ALTER TABLE club_ranking_ranking_entry ADD CONSTRAINT FK_39FF2965296CD8AE FOREIGN KEY (team_id) REFERENCES club_match_team (id) ON DELETE CASCADE;
ALTER TABLE club_ranking_ranking ADD CONSTRAINT FK_977F5D64744E0351 FOREIGN KEY (rule_id) REFERENCES club_ranking_rule (id);
ALTER TABLE club_ranking_users ADD CONSTRAINT FK_A480B4EC20F64684 FOREIGN KEY (ranking_id) REFERENCES club_ranking_ranking (id) ON DELETE CASCADE;
ALTER TABLE club_ranking_users ADD CONSTRAINT FK_A480B4ECA76ED395 FOREIGN KEY (user_id) REFERENCES club_user_user (id) ON DELETE CASCADE;
ALTER TABLE club_user_forgot_password DROP FOREIGN KEY FK_8173F9A7A76ED395;
ALTER TABLE club_user_forgot_password ADD CONSTRAINT FK_8173F9A7A76ED395 FOREIGN KEY (user_id) REFERENCES club_user_user (id) ON DELETE CASCADE;
ALTER TABLE club_user_user ADD api_hash VARCHAR(255) NOT NULL;
ALTER TABLE club_user_profile DROP FOREIGN KEY FK_A3EE1CF532DC9828;
ALTER TABLE club_user_profile DROP FOREIGN KEY FK_A3EE1CF55158A078;
ALTER TABLE club_user_profile DROP FOREIGN KEY FK_A3EE1CF5C219427A;
ALTER TABLE club_user_profile ADD CONSTRAINT FK_A3EE1CF532DC9828 FOREIGN KEY (profile_address_id) REFERENCES club_user_profile_address (id);
ALTER TABLE club_user_profile ADD CONSTRAINT FK_A3EE1CF55158A078 FOREIGN KEY (profile_email_id) REFERENCES club_user_profile_email (id);
ALTER TABLE club_user_profile ADD CONSTRAINT FK_A3EE1CF5C219427A FOREIGN KEY (profile_phone_id) REFERENCES club_user_profile_phone (id);
ALTER TABLE club_shop_product ADD active TINYINT(1) NOT NULL;
ALTER TABLE club_event_event ADD last_subscribe DATETIME NOT NULL, ADD street LONGTEXT DEFAULT NULL, ADD postal_code VARCHAR(255) DEFAULT NULL, ADD city VARCHAR(255) DEFAULT NULL, ADD country VARCHAR(255) DEFAULT NULL, ADD public TINYINT(1) NOT NULL;
ALTER TABLE club_booking_booking ADD status VARCHAR(255) NOT NULL, DROP confirmed;
ALTER TABLE club_booking_plan CHANGE day day VARCHAR(255) NOT NULL;
ALTER TABLE club_match_match ADD tournament_id INT DEFAULT NULL, ADD user_id INT DEFAULT NULL, DROP processed;
ALTER TABLE club_match_match ADD CONSTRAINT FK_1AC3E22F33D1A3E7 FOREIGN KEY (tournament_id) REFERENCES club_tournament_tournament (id);
ALTER TABLE club_match_match ADD CONSTRAINT FK_1AC3E22FA76ED395 FOREIGN KEY (user_id) REFERENCES club_user_user (id);
CREATE INDEX IDX_1AC3E22F33D1A3E7 ON club_match_match (tournament_id);
CREATE INDEX IDX_1AC3E22FA76ED395 ON club_match_match (user_id);
ALTER TABLE club_match_rule CHANGE match_same_player same_player INT NOT NULL
