<?php

namespace Club\MessageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRecipientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRecipientRepository extends EntityRepository
{
}
