<?php

namespace Club\MessageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
  public function getCount()
  {
    return count($this->getQueryBuilder()->getQuery()->getResult());
  }

  public function getWithPagination($offset = 0, $limit = 0)
  {
    return $this->getQueryBuilder()
      ->setFirstResult($offset)
      ->setMaxResults($limit)
      ->getQuery()
      ->getResult();
  }

  private function getQueryBuilder()
  {
    return $this->_em->createQueryBuilder()
      ->select('m')
      ->from('ClubMessageBundle:Message','m')
      ->orderBy('m.id','DESC');
  }

  public function getAllReady()
  {
    return $this->_em->createQueryBuilder()
      ->select('m')
      ->from('ClubMessageBundle:Message','m')
      ->where('m.ready = 1')
      ->andWhere('m.processed = 0')
      ->getQuery()
      ->getResult();
  }
}
