<?php

namespace Club\TournamentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AttendRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttendRepository extends EntityRepository
{
  public function getSeeds(\Club\TournamentBundle\Entity\Tournament $tournament)
  {
    return $this->_em->createQueryBuilder()
      ->select('a')
      ->from('ClubTournamentBundle:Attend', 'a')
      ->where('a.tournament = :tournament')
      ->orderBy('a.seed')
      ->setParameter('tournament', $tournament->getId())
      ->getQuery()
      ->getResult();
  }
}
