<?php

namespace Club\TournamentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TournamentGameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TournamentGameRepository extends EntityRepository
{
}
