<?php

namespace Club\TournamentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TournamentRoundRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TournamentRoundRepository extends EntityRepository
{
}