<?php

namespace Club\BookingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingRepository extends EntityRepository
{
  public function getAllBetween(\DateTime $start, \DateTime $end, \Club\BookingBundle\Entity\Field $field)
  {
    return $this->_em->createQueryBuilder()
      ->select('b')
      ->from('ClubBookingBundle:Booking','b')
      ->where('(b.first_date <= :start and b.end_date >= :end)')
      ->orWhere('(b.first_date <= :start and b.end_date <= :end and b.end_date >= :start)')
      ->orWhere('(b.first_date >= :start and b.end_date >= :end and b.first_date < :end)')
      ->orWhere('(b.first_date >= :start and b.end_date <= :end and b.end_date >= :start)')
      ->orderBy('b.first_date')
      ->setParameter('start', $start->format('Y-m-d H:i:s'))
      ->setParameter('end', $end->format('Y-m-d H:i:s'))
      ->leftJoin('b.field', 'f')
      ->andWhere('f.id = :field')
      ->setParameter('field', $field->getId())
      ->getQuery()
      ->getResult();
  }

  public function getAllByLocationDate(\Club\UserBundle\Entity\Location $location, \DateTime $date)
  {
    return $this->_em->createQueryBuilder()
      ->select('b')
      ->from('ClubBookingBundle:Booking', 'b')
      ->leftJoin('b.field', 'f')
      ->leftJoin('f.location', 'l')
      ->where('l.id = :location')
      ->andWhere('b.first_date BETWEEN :start AND :stop')
      ->setParameter('location', $location->getId())
      ->setParameter('start', $date->format('Y-m-d 00:00:00'))
      ->setParameter('stop', $date->format('Y-m-d 23:59:59'))
      ->getQuery()
      ->getResult();
  }

  public function getIntervals(\Club\BookingBundle\Entity\Booking $booking)
  {
  }

  public function getAllFutureBookings(\Club\UserBundle\Entity\User $user, \DateTime $start)
  {
    return $this->_em->createQueryBuilder()
      ->select('b')
      ->from('ClubBookingBundle:Booking','b')
      ->leftJoin('b.users', 'u')
      ->where('b.first_date >= :start')
      ->andWhere('(b.user = :user OR u.id = :user)')
      ->setParameter('user', $user->getId())
      ->setParameter('start', $start)
      ->getQuery()
      ->getResult();
  }

  public function getLatest(\Club\UserBundle\Entity\User $user, $limit=10)
  {
    $date = new \DateTime();

    return $this->_em->createQueryBuilder()
      ->select('b')
      ->from('ClubBookingBundle:Booking', 'b')
      ->leftJoin('b.users', 'u')
      ->where('b.first_date < :date')
      ->andWhere('(b.user = :user OR u.id = :user)')
      ->setMaxResults($limit)
      ->setParameter('user', $user->getId())
      ->setParameter('date', $date)
      ->getQuery()
      ->getResult();
  }
}
