<?php

namespace Club\BookingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IntervalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IntervalRepository extends EntityRepository
{
  public function getAll(\DateTime $start, \DateTime $end, \Club\BookingBundle\Entity\Field $field)
  {
    return $this->_em->createQueryBuilder()
      ->select('i')
      ->from('ClubBookingBundle:Interval', 'i')
      ->where('((i.start_time <= :start and i.stop_time > :start) or (i.start_time >= :start and i.start_time < :stop))')
      ->andWhere('i.field = :field')
      ->andWhere('i.day = :day')
      ->setParameter('start', $start->format('H:i:s'))
      ->setParameter('stop', $end->format('H:i:s'))
      ->setParameter('field', $field->getId())
      ->setParameter('day', $start->format('N'))
      ->getQuery()
      ->getResult();
  }
}
