<?php

namespace Club\BookingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanRepository extends EntityRepository
{
  public function getAllBetween(\DateTime $start, \DateTime $end, \Club\UserBundle\Entity\Location $location=null, \Club\BookingBundle\Entity\Field $field=null)
  {
    $qb = $this->_em->createQueryBuilder()
      ->select('p')
      ->from('ClubBookingBundle:Plan', 'p')
      ->leftJoin('p.fields', 'f')
      ->where('p.day = :day')
      ->andWhere('p.period_start <= :period_start AND p.period_end >= :period_end')
      ->andWhere('(p.first_time <= :start and p.end_time >= :end) OR (p.first_time <= :start and p.end_time <= :end and p.end_time >= :start) OR (p.first_time >= :start and p.end_time >= :end and p.first_time < :end) OR (p.end_time >= :start and p.end_time <= :end and p.end_time >= :start)')
      ->setParameter('day', $start->format('N'))
      ->setParameter('period_start', $start)
      ->setParameter('period_end', $end)
      ->setParameter('start', $start->format('H:i:s'))
      ->setParameter('end', $end->format('H:i:s'));

    if ($location) {
      $qb
        ->andWhere('f.location = :location')
        ->setParameter('location', $location->getId());
    }

    if ($field) {
      $qb
        ->andWhere('f.id = :field')
        ->setParameter('field', $field->getId());
    }

    return $qb
      ->getQuery()
      ->getResult();
  }
}
