<?php

namespace Club\BookingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanRepository extends EntityRepository
{
  public function getAllBetween(\DateTime $start, \DateTime $end, \Club\UserBundle\Entity\Location $location=null, \Club\BookingBundle\Entity\Field $field=null)
  {
    $qb = $this->_em->createQueryBuilder()
      ->select('p')
      ->from('ClubBookingBundle:Plan', 'p')
      ->leftJoin('p.fields', 'f')
      ->where('p.day = :day AND ((p.period_start <= :start and p.period_end >= :end) OR (p.period_start <= :start and p.period_end <= :end and p.period_end >= :start) OR (p.period_start >= :start and p.period_end >= :end and p.period_start < :end) OR (p.period_start >= :start and p.period_end <= :end and p.period_end >= :start))')
      ->setParameter('day', $start->format('N'))
      ->setParameter('start', $start->format('Y-m-d H:i:s'))
      ->setParameter('end', $end->format('Y-m-d H:i:s'));

    if ($location) {
      $qb
        ->andWhere('f.location = :location')
        ->setParameter('location', $location->getId());
    }

    if ($field) {
      $qb
        ->andWhere('f.id = :field')
        ->setParameter('field', $field->getId());
    }

    return $qb
      ->getQuery()
      ->getResult();
  }
}
