<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20110726110012 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("CREATE TABLE club_shop_product_variantgroup (product_id INT NOT NULL, variantgroup_id INT NOT NULL, INDEX IDX_DB190F384584665A (product_id), INDEX IDX_DB190F38E5B9157C (variantgroup_id), PRIMARY KEY(product_id, variantgroup_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE club_shop_product_variantgroup ADD FOREIGN KEY (product_id) REFERENCES club_shop_product(id)");
        $this->addSql("ALTER TABLE club_shop_product_variantgroup ADD FOREIGN KEY (variantgroup_id) REFERENCES club_shop_variant_group(id)");
        $this->addSql("DROP TABLE product_variantgroup");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("CREATE TABLE product_variantgroup (product_id INT NOT NULL, variantgroup_id INT NOT NULL, INDEX IDX_52B980204584665A (product_id), INDEX IDX_52B98020E5B9157C (variantgroup_id), PRIMARY KEY(product_id, variantgroup_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE product_variantgroup ADD CONSTRAINT product_variantgroup_ibfk_2 FOREIGN KEY (variantgroup_id) REFERENCES club_shop_variant_group(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE product_variantgroup ADD CONSTRAINT product_variantgroup_ibfk_1 FOREIGN KEY (product_id) REFERENCES club_shop_product(id) ON DELETE CASCADE");
        $this->addSql("DROP TABLE club_shop_product_variantgroup");
    }
}
