<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120220135942 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE club_ranking_match_set (id INT AUTO_INCREMENT NOT NULL, match_id INT DEFAULT NULL, game_set INT NOT NULL, value VARCHAR(255) NOT NULL, INDEX IDX_282C5D382ABEACD6 (match_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE club_ranking_match_team_user (id INT AUTO_INCREMENT NOT NULL, match_id INT DEFAULT NULL, user_id INT DEFAULT NULL, INDEX IDX_B6ABBBAC2ABEACD6 (match_id), INDEX IDX_B6ABBBACA76ED395 (user_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE club_ranking_match_set ADD CONSTRAINT FK_282C5D382ABEACD6 FOREIGN KEY (match_id) REFERENCES club_ranking_match(id)");
        $this->addSql("ALTER TABLE club_ranking_match_team_user ADD CONSTRAINT FK_B6ABBBAC2ABEACD6 FOREIGN KEY (match_id) REFERENCES club_ranking_match(id)");
        $this->addSql("ALTER TABLE club_ranking_match_team_user ADD CONSTRAINT FK_B6ABBBACA76ED395 FOREIGN KEY (user_id) REFERENCES club_user_user(id)");
        $this->addSql("ALTER TABLE club_ranking_match ADD CONSTRAINT FK_CA58D400E48FD905 FOREIGN KEY (game_id) REFERENCES club_ranking_game(id)");
        $this->addSql("ALTER TABLE MatchTeam ADD CONSTRAINT FK_AF0633A62ABEACD6 FOREIGN KEY (match_id) REFERENCES club_ranking_match(id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE club_ranking_match_set");
        $this->addSql("DROP TABLE club_ranking_match_team_user");
        $this->addSql("ALTER TABLE MatchTeam DROP FOREIGN KEY FK_AF0633A62ABEACD6");
        $this->addSql("ALTER TABLE club_ranking_match DROP FOREIGN KEY FK_CA58D400E48FD905");
    }
}
