<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20110726110634 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("CREATE TABLE club_mail_mail_location (mail_id INT NOT NULL, location_id INT NOT NULL, INDEX IDX_7D8B38AC8776F01 (mail_id), INDEX IDX_7D8B38A64D218E (location_id), PRIMARY KEY(mail_id, location_id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE club_mail_mail_group (mail_id INT NOT NULL, group_id INT NOT NULL, INDEX IDX_92D63E88C8776F01 (mail_id), INDEX IDX_92D63E88FE54D947 (group_id), PRIMARY KEY(mail_id, group_id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE club_mail_mail_user (mail_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_9483EB90C8776F01 (mail_id), INDEX IDX_9483EB90A76ED395 (user_id), PRIMARY KEY(mail_id, user_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE club_mail_mail_location ADD FOREIGN KEY (mail_id) REFERENCES club_mail(id)");
        $this->addSql("ALTER TABLE club_mail_mail_location ADD FOREIGN KEY (location_id) REFERENCES club_user_location(id)");
        $this->addSql("ALTER TABLE club_mail_mail_group ADD FOREIGN KEY (mail_id) REFERENCES club_mail(id)");
        $this->addSql("ALTER TABLE club_mail_mail_group ADD FOREIGN KEY (group_id) REFERENCES club_user_group(id)");
        $this->addSql("ALTER TABLE club_mail_mail_user ADD FOREIGN KEY (mail_id) REFERENCES club_mail(id)");
        $this->addSql("ALTER TABLE club_mail_mail_user ADD FOREIGN KEY (user_id) REFERENCES club_user_user(id)");
        $this->addSql("DROP TABLE mail_group");
        $this->addSql("DROP TABLE mail_location");
        $this->addSql("DROP TABLE mail_user");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("CREATE TABLE mail_group (mail_id INT NOT NULL, group_id INT NOT NULL, INDEX IDX_5903E6AAC8776F01 (mail_id), INDEX IDX_5903E6AAFE54D947 (group_id), PRIMARY KEY(mail_id, group_id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE mail_location (mail_id INT NOT NULL, location_id INT NOT NULL, INDEX IDX_83494883C8776F01 (mail_id), INDEX IDX_8349488364D218E (location_id), PRIMARY KEY(mail_id, location_id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE mail_user (mail_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_20E84520C8776F01 (mail_id), INDEX IDX_20E84520A76ED395 (user_id), PRIMARY KEY(mail_id, user_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE mail_group ADD CONSTRAINT mail_group_ibfk_2 FOREIGN KEY (group_id) REFERENCES club_user_group(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE mail_group ADD CONSTRAINT mail_group_ibfk_1 FOREIGN KEY (mail_id) REFERENCES club_mail(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE mail_location ADD CONSTRAINT mail_location_ibfk_2 FOREIGN KEY (location_id) REFERENCES club_user_location(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE mail_location ADD CONSTRAINT mail_location_ibfk_1 FOREIGN KEY (mail_id) REFERENCES club_mail(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE mail_user ADD CONSTRAINT mail_user_ibfk_2 FOREIGN KEY (user_id) REFERENCES club_user_user(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE mail_user ADD CONSTRAINT mail_user_ibfk_1 FOREIGN KEY (mail_id) REFERENCES club_mail(id) ON DELETE CASCADE");
        $this->addSql("DROP TABLE club_mail_mail_location");
        $this->addSql("DROP TABLE club_mail_mail_group");
        $this->addSql("DROP TABLE club_mail_mail_user");
    }
}
