<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20111007182324 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_shop_coupon ADD updated_at DATETIME NOT NULL");
        $this->addSql("ALTER TABLE club_shop_subscription_pause CHANGE old_expire_date old_expire_date DATETIME NOT NULL, CHANGE start_date start_date DATETIME NOT NULL, CHANGE expire_date expire_date DATETIME DEFAULT NULL");
        $this->addSql("ALTER TABLE club_shop_subscription CHANGE start_date start_date DATETIME NOT NULL, CHANGE expire_date expire_date DATETIME DEFAULT NULL");
        $this->addSql("CREATE INDEX active_idx ON club_shop_subscription (active)");
        $this->addSql("ALTER TABLE club_shop_order ADD location_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE club_shop_order ADD CONSTRAINT FK_7BF9872764D218E FOREIGN KEY (location_id) REFERENCES club_user_location(id)");
        $this->addSql("CREATE INDEX IDX_7BF9872764D218E ON club_shop_order (location_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_shop_coupon DROP updated_at");
        $this->addSql("ALTER TABLE club_shop_order DROP FOREIGN KEY FK_7BF9872764D218E");
        $this->addSql("DROP INDEX IDX_7BF9872764D218E ON club_shop_order");
        $this->addSql("ALTER TABLE club_shop_order DROP location_id");
        $this->addSql("DROP INDEX active_idx ON club_shop_subscription");
        $this->addSql("ALTER TABLE club_shop_subscription CHANGE start_date start_date DATE NOT NULL, CHANGE expire_date expire_date DATE DEFAULT NULL");
        $this->addSql("ALTER TABLE club_shop_subscription_pause CHANGE old_expire_date old_expire_date DATE NOT NULL, CHANGE start_date start_date DATE NOT NULL, CHANGE expire_date expire_date DATE DEFAULT NULL");
    }
}
