<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120312224547 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE club_payment_quickpay_transaction (id INT AUTO_INCREMENT NOT NULL, msgtype VARCHAR(255) NOT NULL, ordernumber VARCHAR(255) NOT NULL, amount VARCHAR(255) NOT NULL, currency VARCHAR(255) NOT NULL, time VARCHAR(255) NOT NULL, state VARCHAR(255) NOT NULL, qpstat VARCHAR(255) NOT NULL, qpstatmsg VARCHAR(255) NOT NULL, chstat VARCHAR(255) NOT NULL, chstatmsg VARCHAR(255) NOT NULL, merchant VARCHAR(255) NOT NULL, merchantemail VARCHAR(255) NOT NULL, transaction VARCHAR(255) NOT NULL, cardtype VARCHAR(255) NOT NULL, cardnumber VARCHAR(255) NOT NULL, cardexpire VARCHAR(255) NOT NULL, splitpayment VARCHAR(255) NOT NULL, fraudprobability VARCHAR(255) NOT NULL, fraudremarks VARCHAR(255) NOT NULL, fraudreport VARCHAR(255) NOT NULL, fee VARCHAR(255) NOT NULL, md5check VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("DROP TABLE Transaction");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE Transaction (id INT AUTO_INCREMENT NOT NULL, msgtype VARCHAR(255) NOT NULL, ordernumber VARCHAR(255) NOT NULL, amount VARCHAR(255) NOT NULL, currency VARCHAR(255) NOT NULL, time VARCHAR(255) NOT NULL, state VARCHAR(255) NOT NULL, qpstat VARCHAR(255) NOT NULL, qpstatmsg VARCHAR(255) NOT NULL, chstat VARCHAR(255) NOT NULL, chstatmsg VARCHAR(255) NOT NULL, merchant VARCHAR(255) NOT NULL, merchantemail VARCHAR(255) NOT NULL, transaction VARCHAR(255) NOT NULL, cardtype VARCHAR(255) NOT NULL, cardnumber VARCHAR(255) NOT NULL, cardexpire VARCHAR(255) NOT NULL, splitpayment VARCHAR(255) NOT NULL, fraudprobability VARCHAR(255) NOT NULL, fraudremarks VARCHAR(255) NOT NULL, fraudreport VARCHAR(255) NOT NULL, fee VARCHAR(255) NOT NULL, md5check VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("DROP TABLE club_payment_quickpay_transaction");
    }
}
