<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120417114853 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_match_league_table ADD won INT NOT NULL, ADD lost INT NOT NULL, DROP win, DROP loss");
        $this->addSql("ALTER TABLE club_match_rule CHANGE point_loss point_lost INT NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_match_league_table ADD win INT NOT NULL, ADD loss INT NOT NULL, DROP won, DROP lost");
        $this->addSql("ALTER TABLE club_match_rule CHANGE point_lost point_loss INT NOT NULL");
    }
}
