<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20111121212420 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_booking_interval ADD location_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE club_booking_interval ADD CONSTRAINT FK_438698A764D218E FOREIGN KEY (location_id) REFERENCES club_user_location(id)");
        $this->addSql("CREATE INDEX IDX_438698A764D218E ON club_booking_interval (location_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_booking_interval DROP FOREIGN KEY FK_438698A764D218E");
        $this->addSql("DROP INDEX IDX_438698A764D218E ON club_booking_interval");
        $this->addSql("ALTER TABLE club_booking_interval DROP location_id");
    }
}
