<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120211150121 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("CREATE TABLE club_booking_plan_field (plan_id INT NOT NULL, field_id INT NOT NULL, INDEX IDX_F7A9AD0E899029B (plan_id), INDEX IDX_F7A9AD0443707B0 (field_id), PRIMARY KEY(plan_id, field_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE club_booking_plan_field ADD CONSTRAINT FK_F7A9AD0E899029B FOREIGN KEY (plan_id) REFERENCES club_booking_plan(id)");
        $this->addSql("ALTER TABLE club_booking_plan_field ADD CONSTRAINT FK_F7A9AD0443707B0 FOREIGN KEY (field_id) REFERENCES club_booking_field(id)");
        $this->addSql("DROP TABLE plan_field");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("CREATE TABLE plan_field (plan_id INT NOT NULL, field_id INT NOT NULL, INDEX IDX_85300A4E899029B (plan_id), INDEX IDX_85300A4443707B0 (field_id), PRIMARY KEY(plan_id, field_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE plan_field ADD CONSTRAINT FK_85300A4443707B0 FOREIGN KEY (field_id) REFERENCES club_booking_field(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE plan_field ADD CONSTRAINT FK_85300A4E899029B FOREIGN KEY (plan_id) REFERENCES club_booking_plan(id) ON DELETE CASCADE");
        $this->addSql("DROP TABLE club_booking_plan_field");
    }
}
