<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20110719111200 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_shop_coupon_log ADD user_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE club_shop_coupon_log ADD FOREIGN KEY (user_id) REFERENCES club_user_user(id)");
        $this->addSql("CREATE INDEX IDX_B8DD3D7A76ED395 ON club_shop_coupon_log (user_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_shop_coupon_log DROP FOREIGN KEY ");
        $this->addSql("DROP INDEX IDX_B8DD3D7A76ED395 ON club_shop_coupon_log");
        $this->addSql("ALTER TABLE club_shop_coupon_log DROP user_id");
    }
}
