<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20110629215231 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_user_group_role DROP FOREIGN KEY club_user_group_role_ibfk_2");
        $this->addSql("ALTER TABLE club_user_group_role DROP FOREIGN KEY club_user_group_role_ibfk_1");
        $this->addSql("ALTER TABLE club_user_group_role ADD FOREIGN KEY (group_id) REFERENCES club_user_group(id)");
        $this->addSql("ALTER TABLE club_user_group_role ADD FOREIGN KEY (role_id) REFERENCES club_user_role(id)");
        $this->addSql("ALTER TABLE club_user_user CHANGE activation_code activation_code VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE club_user_currency ADD is_active TINYINT(1) NOT NULL, ADD created_at DATETIME NOT NULL, ADD updated_at DATETIME NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_user_currency DROP is_active, DROP created_at, DROP updated_at");
        $this->addSql("ALTER TABLE club_user_group_role DROP FOREIGN KEY ");
        $this->addSql("ALTER TABLE club_user_group_role DROP FOREIGN KEY ");
        $this->addSql("ALTER TABLE club_user_group_role ADD CONSTRAINT club_user_group_role_ibfk_2 FOREIGN KEY (role_id) REFERENCES club_user_role(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE club_user_group_role ADD CONSTRAINT club_user_group_role_ibfk_1 FOREIGN KEY (group_id) REFERENCES club_user_group(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE club_user_user CHANGE activation_code activation_code VARCHAR(255) NOT NULL");
    }
}
