<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120220155818 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_ranking_match_team_user DROP FOREIGN KEY FK_B6ABBBAC2ABEACD6");
        $this->addSql("DROP INDEX IDX_B6ABBBAC2ABEACD6 ON club_ranking_match_team_user");
        $this->addSql("ALTER TABLE club_ranking_match_team_user CHANGE match_id match_team_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE club_ranking_match_team_user ADD CONSTRAINT FK_B6ABBBAC5ECA87C1 FOREIGN KEY (match_team_id) REFERENCES club_ranking_match_team(id)");
        $this->addSql("CREATE INDEX IDX_B6ABBBAC5ECA87C1 ON club_ranking_match_team_user (match_team_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_ranking_match_team_user DROP FOREIGN KEY FK_B6ABBBAC5ECA87C1");
        $this->addSql("DROP INDEX IDX_B6ABBBAC5ECA87C1 ON club_ranking_match_team_user");
        $this->addSql("ALTER TABLE club_ranking_match_team_user CHANGE match_team_id match_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE club_ranking_match_team_user ADD CONSTRAINT FK_B6ABBBAC2ABEACD6 FOREIGN KEY (match_id) REFERENCES club_ranking_match(id)");
        $this->addSql("CREATE INDEX IDX_B6ABBBAC2ABEACD6 ON club_ranking_match_team_user (match_id)");
    }
}
