<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20111003171857 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE club_mail_log (id INT AUTO_INCREMENT NOT NULL, message LONGTEXT NOT NULL, recipient VARCHAR(255) NOT NULL, error TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("DROP TABLE club_message_message_queue");
        $this->addSql("ALTER TABLE club_message_message ADD ready TINYINT(1) NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE club_message_message_queue (id INT AUTO_INCREMENT NOT NULL, message_id INT DEFAULT NULL, user_id INT DEFAULT NULL, error_message VARCHAR(255) DEFAULT NULL, processed TINYINT(1) NOT NULL, updated_at DATETIME NOT NULL, created_at DATETIME NOT NULL, recipient VARCHAR(255) NOT NULL, INDEX IDX_582BBC47A76ED395 (user_id), INDEX IDX_582BBC47537A1329 (message_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE club_message_message_queue ADD CONSTRAINT FK_582BBC47537A1329 FOREIGN KEY (message_id) REFERENCES club_message_message(id)");
        $this->addSql("ALTER TABLE club_message_message_queue ADD CONSTRAINT FK_582BBC47A76ED395 FOREIGN KEY (user_id) REFERENCES club_user_user(id)");
        $this->addSql("DROP TABLE club_mail_log");
        $this->addSql("ALTER TABLE club_message_message DROP ready");
    }
}
