<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120220123303 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_ranking_game ADD rule_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE club_ranking_game ADD CONSTRAINT FK_F0A216F6744E0351 FOREIGN KEY (rule_id) REFERENCES club_ranking_rule(id)");
        $this->addSql("CREATE INDEX IDX_F0A216F6744E0351 ON club_ranking_game (rule_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_ranking_game DROP FOREIGN KEY FK_F0A216F6744E0351");
        $this->addSql("DROP INDEX IDX_F0A216F6744E0351 ON club_ranking_game");
        $this->addSql("ALTER TABLE club_ranking_game DROP rule_id");
    }
}
