<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20111007174652 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_shop_order ADD location_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE club_shop_order ADD CONSTRAINT FK_7BF9872764D218E FOREIGN KEY (location_id) REFERENCES club_user_location(id)");
        $this->addSql("CREATE INDEX IDX_7BF9872764D218E ON club_shop_order (location_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_shop_order DROP FOREIGN KEY FK_7BF9872764D218E");
        $this->addSql("DROP INDEX IDX_7BF9872764D218E ON club_shop_order");
        $this->addSql("ALTER TABLE club_shop_order DROP location_id");
    }
}
