<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20110726105407 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("CREATE TABLE club_user_group_product (group_id INT NOT NULL, product_id INT NOT NULL, INDEX IDX_257704F4FE54D947 (group_id), INDEX IDX_257704F44584665A (product_id), PRIMARY KEY(group_id, product_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE club_user_group_product ADD FOREIGN KEY (group_id) REFERENCES club_user_group(id)");
        $this->addSql("ALTER TABLE club_user_group_product ADD FOREIGN KEY (product_id) REFERENCES club_shop_product(id)");
        $this->addSql("DROP TABLE group_product");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("CREATE TABLE group_product (group_id INT NOT NULL, product_id INT NOT NULL, INDEX IDX_554A50A1FE54D947 (group_id), INDEX IDX_554A50A14584665A (product_id), PRIMARY KEY(group_id, product_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE group_product ADD CONSTRAINT group_product_ibfk_2 FOREIGN KEY (product_id) REFERENCES club_shop_product(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE group_product ADD CONSTRAINT group_product_ibfk_1 FOREIGN KEY (group_id) REFERENCES club_user_group(id) ON DELETE CASCADE");
        $this->addSql("DROP TABLE club_user_group_product");
    }
}
