<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120313082243 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE club_user_location DROP FOREIGN KEY FK_3D42B7FF92F3E70");
        $this->addSql("ALTER TABLE club_user_profile_address DROP FOREIGN KEY FK_753AFDDCF92F3E70");
        $this->addSql("DROP TABLE club_user_country");
        $this->addSql("DROP INDEX IDX_3D42B7FF92F3E70 ON club_user_location");
        $this->addSql("ALTER TABLE club_user_location ADD country VARCHAR(255) NOT NULL, DROP country_id");
        $this->addSql("DROP INDEX IDX_753AFDDCF92F3E70 ON club_user_profile_address");
        $this->addSql("ALTER TABLE club_user_profile_address ADD country VARCHAR(255) NOT NULL, DROP country_id");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("CREATE TABLE club_user_country (id INT AUTO_INCREMENT NOT NULL, country VARCHAR(255) NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE club_user_location ADD country_id INT DEFAULT NULL, DROP country");
        $this->addSql("ALTER TABLE club_user_location ADD CONSTRAINT FK_3D42B7FF92F3E70 FOREIGN KEY (country_id) REFERENCES club_user_country(id)");
        $this->addSql("CREATE INDEX IDX_3D42B7FF92F3E70 ON club_user_location (country_id)");
        $this->addSql("ALTER TABLE club_user_profile_address ADD country_id INT DEFAULT NULL, DROP country");
        $this->addSql("ALTER TABLE club_user_profile_address ADD CONSTRAINT FK_753AFDDCF92F3E70 FOREIGN KEY (country_id) REFERENCES club_user_country(id)");
        $this->addSql("CREATE INDEX IDX_753AFDDCF92F3E70 ON club_user_profile_address (country_id)");
    }
}
