<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20111107133303 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_team_repetition ADD type VARCHAR(255) NOT NULL, CHANGE last_date last_date DATETIME DEFAULT NULL, CHANGE day_of_month day_of_month TINYINT(1) DEFAULT NULL, CHANGE end_occurrences end_occurrences INT DEFAULT NULL, CHANGE repeat_every repeat_every INT DEFAULT NULL, CHANGE days_in_week days_in_week INT DEFAULT NULL, CHANGE week week VARCHAR(255) DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_team_repetition DROP type, CHANGE last_date last_date DATETIME NOT NULL, CHANGE end_occurrences end_occurrences INT NOT NULL, CHANGE repeat_every repeat_every INT NOT NULL, CHANGE days_in_week days_in_week INT NOT NULL, CHANGE day_of_month day_of_month TINYINT(1) NOT NULL, CHANGE week week VARCHAR(255) NOT NULL");
    }
}
