<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120406225014 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_booking_plan_field DROP FOREIGN KEY FK_F7A9AD0E899029B");
        $this->addSql("ALTER TABLE club_booking_plan_field ADD CONSTRAINT FK_F7A9AD0E899029B FOREIGN KEY (plan_id) REFERENCES club_booking_plan(id) ON DELETE CASCADE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_booking_plan_field DROP FOREIGN KEY FK_F7A9AD0E899029B");
        $this->addSql("ALTER TABLE club_booking_plan_field ADD CONSTRAINT FK_F7A9AD0E899029B FOREIGN KEY (plan_id) REFERENCES club_booking_plan(id)");
    }
}
