<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120412203128 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE club_booking_plan DROP FOREIGN KEY FK_BF7FD1C3E6FF4589");
        $this->addSql("DROP TABLE club_booking_plan_category");
        $this->addSql("DROP INDEX IDX_BF7FD1C3E6FF4589 ON club_booking_plan");
        $this->addSql("ALTER TABLE club_booking_plan DROP plan_category_id");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("CREATE TABLE club_booking_plan_category (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_92CD14CCA76ED395 (user_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE club_booking_plan_category ADD CONSTRAINT FK_92CD14CCA76ED395 FOREIGN KEY (user_id) REFERENCES club_user_user(id)");
        $this->addSql("ALTER TABLE club_booking_plan ADD plan_category_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE club_booking_plan ADD CONSTRAINT FK_BF7FD1C3E6FF4589 FOREIGN KEY (plan_category_id) REFERENCES club_booking_plan_category(id) ON DELETE CASCADE");
        $this->addSql("CREATE INDEX IDX_BF7FD1C3E6FF4589 ON club_booking_plan (plan_category_id)");
    }
}
