<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20110712124146 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_user_filter_attribute DROP FOREIGN KEY club_user_filter_attribute_ibfk_2");
        $this->addSql("ALTER TABLE club_user_filter_attribute ADD FOREIGN KEY (filter_id) REFERENCES club_user_filter(id) ON DELETE CASCADE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_user_filter_attribute DROP FOREIGN KEY ");
        $this->addSql("ALTER TABLE club_user_filter_attribute ADD CONSTRAINT club_user_filter_attribute_ibfk_2 FOREIGN KEY (filter_id) REFERENCES club_user_filter(id)");
    }
}
