<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120131103102 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_event_attend DROP paid");
        $this->addSql("ALTER TABLE club_event_event DROP price");
        $this->addSql("ALTER TABLE club_booking_field CHANGE information information LONGTEXT DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_booking_field CHANGE information information LONGTEXT NOT NULL");
        $this->addSql("ALTER TABLE club_event_attend ADD paid TINYINT(1) NOT NULL");
        $this->addSql("ALTER TABLE club_event_event ADD price NUMERIC(10, 2) DEFAULT NULL");
    }
}
