<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20110726131548 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE club_mail_attachment DROP FOREIGN KEY club_mail_attachment_ibfk_1");
        $this->addSql("ALTER TABLE club_mail_mail_group DROP FOREIGN KEY club_mail_mail_group_ibfk_1");
        $this->addSql("ALTER TABLE club_mail_mail_location DROP FOREIGN KEY club_mail_mail_location_ibfk_1");
        $this->addSql("ALTER TABLE club_mail_mail_user DROP FOREIGN KEY club_mail_mail_user_ibfk_1");
        $this->addSql("CREATE TABLE club_message_message_attachment (id INT AUTO_INCREMENT NOT NULL, message_id INT DEFAULT NULL, file_path VARCHAR(255) NOT NULL, file_name VARCHAR(255) NOT NULL, file_type VARCHAR(255) NOT NULL, file_size VARCHAR(255) NOT NULL, file_hash VARCHAR(255) NOT NULL, INDEX IDX_7A27EA70537A1329 (message_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE club_message_message (id INT AUTO_INCREMENT NOT NULL, subject VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, message LONGTEXT NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE club_message_message_attachment ADD FOREIGN KEY (message_id) REFERENCES club_message_message(id)");
        $this->addSql("DROP TABLE club_mail");
        $this->addSql("DROP TABLE club_mail_attachment");
        $this->addSql("DROP TABLE club_mail_queue");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE club_message_message_attachment DROP FOREIGN KEY ");
        $this->addSql("ALTER TABLE club_mail_mail_location DROP FOREIGN KEY ");
        $this->addSql("ALTER TABLE club_mail_mail_group DROP FOREIGN KEY ");
        $this->addSql("ALTER TABLE club_mail_mail_user DROP FOREIGN KEY ");
        $this->addSql("CREATE TABLE club_mail (id INT AUTO_INCREMENT NOT NULL, subject VARCHAR(255) NOT NULL, body LONGTEXT NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE club_mail_attachment (id INT AUTO_INCREMENT NOT NULL, mail_id INT DEFAULT NULL, file_path VARCHAR(255) NOT NULL, file_name VARCHAR(255) NOT NULL, file_type VARCHAR(255) NOT NULL, file_size VARCHAR(255) NOT NULL, file_hash VARCHAR(255) NOT NULL, INDEX IDX_B28A0199C8776F01 (mail_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE club_mail_queue (id INT AUTO_INCREMENT NOT NULL, message LONGTEXT NOT NULL, error_message VARCHAR(255) NOT NULL, priority INT NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE club_mail_attachment ADD CONSTRAINT club_mail_attachment_ibfk_1 FOREIGN KEY (mail_id) REFERENCES club_mail(id)");
        $this->addSql("DROP TABLE club_message_message_attachment");
        $this->addSql("DROP TABLE club_message_message");
    }
}
