<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120416145803 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE club_ranking_game_user DROP FOREIGN KEY FK_ACF0635FE48FD905");
        $this->addSql("ALTER TABLE club_ranking_match DROP FOREIGN KEY FK_CA58D400E48FD905");
        $this->addSql("ALTER TABLE club_ranking_match_comment DROP FOREIGN KEY FK_FCC8EEA72ABEACD6");
        $this->addSql("ALTER TABLE club_ranking_match_team DROP FOREIGN KEY FK_6349B8062ABEACD6");
        $this->addSql("ALTER TABLE club_ranking_match DROP FOREIGN KEY FK_CA58D4005DFCD4B8");
        $this->addSql("ALTER TABLE club_ranking_match_team_set DROP FOREIGN KEY FK_B05908FC5ECA87C1");
        $this->addSql("ALTER TABLE club_ranking_match_team_user DROP FOREIGN KEY FK_B6ABBBAC5ECA87C1");
        $this->addSql("ALTER TABLE club_ranking_game DROP FOREIGN KEY FK_F0A216F6744E0351");
        $this->addSql("ALTER TABLE club_ranking_match_team DROP FOREIGN KEY FK_6349B806296CD8AE");
        $this->addSql("ALTER TABLE club_ranking_team_user DROP FOREIGN KEY FK_9604FB08296CD8AE");
        $this->addSql("CREATE TABLE club_match_game (id INT AUTO_INCREMENT NOT NULL, rule_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, invite_only TINYINT(1) NOT NULL, game_set INT NOT NULL, type VARCHAR(255) NOT NULL, start_date DATETIME NOT NULL, end_date DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_B82CE13744E0351 (rule_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE club_match_game_user (game_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_6021C410E48FD905 (game_id), INDEX IDX_6021C410A76ED395 (user_id), PRIMARY KEY(game_id, user_id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE club_match_match (id INT AUTO_INCREMENT NOT NULL, winner_id INT DEFAULT NULL, game_id INT DEFAULT NULL, display_result VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_1AC3E22F5DFCD4B8 (winner_id), INDEX IDX_1AC3E22FE48FD905 (game_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE club_match_match_team_set (id INT AUTO_INCREMENT NOT NULL, match_team_id INT DEFAULT NULL, game_set INT NOT NULL, value VARCHAR(255) NOT NULL, INDEX IDX_5142219D5ECA87C1 (match_team_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE club_match_match_comment (id INT AUTO_INCREMENT NOT NULL, match_id INT DEFAULT NULL, user_id INT DEFAULT NULL, comment LONGTEXT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_E97997EC2ABEACD6 (match_id), INDEX IDX_E97997ECA76ED395 (user_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE club_match_rule (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, point_won INT NOT NULL, point_loss INT NOT NULL, match_same_player INT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE club_match_team (id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE club_match_team_user (team_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_5AD55C47296CD8AE (team_id), INDEX IDX_5AD55C47A76ED395 (user_id), PRIMARY KEY(team_id, user_id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE club_match_match_team (id INT AUTO_INCREMENT NOT NULL, match_id INT DEFAULT NULL, team_id INT DEFAULT NULL, INDEX IDX_85E635A02ABEACD6 (match_id), INDEX IDX_85E635A0296CD8AE (team_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE club_match_match_team_user (id INT AUTO_INCREMENT NOT NULL, match_team_id INT DEFAULT NULL, user_id INT DEFAULT NULL, INDEX IDX_8CFFF14B5ECA87C1 (match_team_id), INDEX IDX_8CFFF14BA76ED395 (user_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE club_match_game ADD CONSTRAINT FK_B82CE13744E0351 FOREIGN KEY (rule_id) REFERENCES club_match_rule(id)");
        $this->addSql("ALTER TABLE club_match_game_user ADD CONSTRAINT FK_6021C410E48FD905 FOREIGN KEY (game_id) REFERENCES club_match_game(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE club_match_game_user ADD CONSTRAINT FK_6021C410A76ED395 FOREIGN KEY (user_id) REFERENCES club_user_user(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE club_match_match ADD CONSTRAINT FK_1AC3E22F5DFCD4B8 FOREIGN KEY (winner_id) REFERENCES club_match_match_team(id)");
        $this->addSql("ALTER TABLE club_match_match ADD CONSTRAINT FK_1AC3E22FE48FD905 FOREIGN KEY (game_id) REFERENCES club_match_game(id)");
        $this->addSql("ALTER TABLE club_match_match_team_set ADD CONSTRAINT FK_5142219D5ECA87C1 FOREIGN KEY (match_team_id) REFERENCES club_match_match_team(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE club_match_match_comment ADD CONSTRAINT FK_E97997EC2ABEACD6 FOREIGN KEY (match_id) REFERENCES club_match_match(id)");
        $this->addSql("ALTER TABLE club_match_match_comment ADD CONSTRAINT FK_E97997ECA76ED395 FOREIGN KEY (user_id) REFERENCES club_user_user(id)");
        $this->addSql("ALTER TABLE club_match_team_user ADD CONSTRAINT FK_5AD55C47296CD8AE FOREIGN KEY (team_id) REFERENCES club_match_team(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE club_match_team_user ADD CONSTRAINT FK_5AD55C47A76ED395 FOREIGN KEY (user_id) REFERENCES club_user_user(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE club_match_match_team ADD CONSTRAINT FK_85E635A02ABEACD6 FOREIGN KEY (match_id) REFERENCES club_match_match(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE club_match_match_team ADD CONSTRAINT FK_85E635A0296CD8AE FOREIGN KEY (team_id) REFERENCES club_match_team(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE club_match_match_team_user ADD CONSTRAINT FK_8CFFF14B5ECA87C1 FOREIGN KEY (match_team_id) REFERENCES club_match_match_team(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE club_match_match_team_user ADD CONSTRAINT FK_8CFFF14BA76ED395 FOREIGN KEY (user_id) REFERENCES club_user_user(id)");
        $this->addSql("DROP TABLE club_ranking_game");
        $this->addSql("DROP TABLE club_ranking_game_user");
        $this->addSql("DROP TABLE club_ranking_match");
        $this->addSql("DROP TABLE club_ranking_match_comment");
        $this->addSql("DROP TABLE club_ranking_match_team");
        $this->addSql("DROP TABLE club_ranking_match_team_set");
        $this->addSql("DROP TABLE club_ranking_match_team_user");
        $this->addSql("DROP TABLE club_ranking_rule");
        $this->addSql("DROP TABLE club_ranking_team");
        $this->addSql("DROP TABLE club_ranking_team_user");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE club_match_game_user DROP FOREIGN KEY FK_6021C410E48FD905");
        $this->addSql("ALTER TABLE club_match_match DROP FOREIGN KEY FK_1AC3E22FE48FD905");
        $this->addSql("ALTER TABLE club_match_match_comment DROP FOREIGN KEY FK_E97997EC2ABEACD6");
        $this->addSql("ALTER TABLE club_match_match_team DROP FOREIGN KEY FK_85E635A02ABEACD6");
        $this->addSql("ALTER TABLE club_match_game DROP FOREIGN KEY FK_B82CE13744E0351");
        $this->addSql("ALTER TABLE club_match_team_user DROP FOREIGN KEY FK_5AD55C47296CD8AE");
        $this->addSql("ALTER TABLE club_match_match_team DROP FOREIGN KEY FK_85E635A0296CD8AE");
        $this->addSql("ALTER TABLE club_match_match DROP FOREIGN KEY FK_1AC3E22F5DFCD4B8");
        $this->addSql("ALTER TABLE club_match_match_team_set DROP FOREIGN KEY FK_5142219D5ECA87C1");
        $this->addSql("ALTER TABLE club_match_match_team_user DROP FOREIGN KEY FK_8CFFF14B5ECA87C1");
        $this->addSql("CREATE TABLE club_ranking_game (id INT AUTO_INCREMENT NOT NULL, rule_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, invite_only TINYINT(1) NOT NULL, game_set INT NOT NULL, type VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, start_date DATETIME NOT NULL, end_date DATETIME DEFAULT NULL, INDEX IDX_F0A216F6744E0351 (rule_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE club_ranking_game_user (game_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_ACF0635FE48FD905 (game_id), INDEX IDX_ACF0635FA76ED395 (user_id), PRIMARY KEY(game_id, user_id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE club_ranking_match (id INT AUTO_INCREMENT NOT NULL, winner_id INT DEFAULT NULL, game_id INT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, display_result VARCHAR(255) NOT NULL, INDEX IDX_CA58D400E48FD905 (game_id), INDEX IDX_CA58D4005DFCD4B8 (winner_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE club_ranking_match_comment (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, match_id INT DEFAULT NULL, comment LONGTEXT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_FCC8EEA72ABEACD6 (match_id), INDEX IDX_FCC8EEA7A76ED395 (user_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE club_ranking_match_team (id INT AUTO_INCREMENT NOT NULL, team_id INT DEFAULT NULL, match_id INT DEFAULT NULL, INDEX IDX_6349B8062ABEACD6 (match_id), INDEX IDX_6349B806296CD8AE (team_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE club_ranking_match_team_set (id INT AUTO_INCREMENT NOT NULL, match_team_id INT DEFAULT NULL, game_set INT NOT NULL, value VARCHAR(255) NOT NULL, INDEX IDX_B05908FC5ECA87C1 (match_team_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE club_ranking_match_team_user (id INT AUTO_INCREMENT NOT NULL, match_team_id INT DEFAULT NULL, user_id INT DEFAULT NULL, INDEX IDX_B6ABBBAC5ECA87C1 (match_team_id), INDEX IDX_B6ABBBACA76ED395 (user_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE club_ranking_rule (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, point_won INT NOT NULL, point_loss INT NOT NULL, match_same_player INT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE club_ranking_team (id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE club_ranking_team_user (team_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_9604FB08296CD8AE (team_id), INDEX IDX_9604FB08A76ED395 (user_id), PRIMARY KEY(team_id, user_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE club_ranking_game ADD CONSTRAINT FK_F0A216F6744E0351 FOREIGN KEY (rule_id) REFERENCES club_ranking_rule(id)");
        $this->addSql("ALTER TABLE club_ranking_game_user ADD CONSTRAINT FK_ACF0635FA76ED395 FOREIGN KEY (user_id) REFERENCES club_user_user(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE club_ranking_game_user ADD CONSTRAINT FK_ACF0635FE48FD905 FOREIGN KEY (game_id) REFERENCES club_ranking_game(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE club_ranking_match ADD CONSTRAINT FK_CA58D4005DFCD4B8 FOREIGN KEY (winner_id) REFERENCES club_ranking_match_team(id)");
        $this->addSql("ALTER TABLE club_ranking_match ADD CONSTRAINT FK_CA58D400E48FD905 FOREIGN KEY (game_id) REFERENCES club_ranking_game(id)");
        $this->addSql("ALTER TABLE club_ranking_match_comment ADD CONSTRAINT FK_FCC8EEA7A76ED395 FOREIGN KEY (user_id) REFERENCES club_user_user(id)");
        $this->addSql("ALTER TABLE club_ranking_match_comment ADD CONSTRAINT FK_FCC8EEA72ABEACD6 FOREIGN KEY (match_id) REFERENCES club_ranking_match(id)");
        $this->addSql("ALTER TABLE club_ranking_match_team ADD CONSTRAINT FK_6349B806296CD8AE FOREIGN KEY (team_id) REFERENCES club_ranking_team(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE club_ranking_match_team ADD CONSTRAINT FK_6349B8062ABEACD6 FOREIGN KEY (match_id) REFERENCES club_ranking_match(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE club_ranking_match_team_set ADD CONSTRAINT FK_B05908FC5ECA87C1 FOREIGN KEY (match_team_id) REFERENCES club_ranking_match_team(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE club_ranking_match_team_user ADD CONSTRAINT FK_B6ABBBAC5ECA87C1 FOREIGN KEY (match_team_id) REFERENCES club_ranking_match_team(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE club_ranking_match_team_user ADD CONSTRAINT FK_B6ABBBACA76ED395 FOREIGN KEY (user_id) REFERENCES club_user_user(id)");
        $this->addSql("ALTER TABLE club_ranking_team_user ADD CONSTRAINT FK_9604FB08A76ED395 FOREIGN KEY (user_id) REFERENCES club_user_user(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE club_ranking_team_user ADD CONSTRAINT FK_9604FB08296CD8AE FOREIGN KEY (team_id) REFERENCES club_ranking_team(id) ON DELETE CASCADE");
        $this->addSql("DROP TABLE club_match_game");
        $this->addSql("DROP TABLE club_match_game_user");
        $this->addSql("DROP TABLE club_match_match");
        $this->addSql("DROP TABLE club_match_match_team_set");
        $this->addSql("DROP TABLE club_match_match_comment");
        $this->addSql("DROP TABLE club_match_rule");
        $this->addSql("DROP TABLE club_match_team");
        $this->addSql("DROP TABLE club_match_team_user");
        $this->addSql("DROP TABLE club_match_match_team");
        $this->addSql("DROP TABLE club_match_match_team_user");
    }
}
