<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20111118123617 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE club_booking_day (id INT AUTO_INCREMENT NOT NULL, field_id INT DEFAULT NULL, day VARCHAR(255) NOT NULL, open_date DATETIME NOT NULL, close_date DATETIME NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_1D3748CC443707B0 (field_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE club_booking_field (id INT AUTO_INCREMENT NOT NULL, location_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, position INT NOT NULL, terms LONGTEXT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_774EFE5964D218E (location_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE club_booking_interval (id INT AUTO_INCREMENT NOT NULL, day_id INT DEFAULT NULL, start_time TIME NOT NULL, stop_time TIME NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_438698A79C24126 (day_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE club_booking_day ADD CONSTRAINT FK_1D3748CC443707B0 FOREIGN KEY (field_id) REFERENCES club_booking_field(id)");
        $this->addSql("ALTER TABLE club_booking_field ADD CONSTRAINT FK_774EFE5964D218E FOREIGN KEY (location_id) REFERENCES club_user_location(id)");
        $this->addSql("ALTER TABLE club_booking_interval ADD CONSTRAINT FK_438698A79C24126 FOREIGN KEY (day_id) REFERENCES club_booking_day(id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_booking_interval DROP FOREIGN KEY FK_438698A79C24126");
        $this->addSql("ALTER TABLE club_booking_day DROP FOREIGN KEY FK_1D3748CC443707B0");
        $this->addSql("DROP TABLE club_booking_day");
        $this->addSql("DROP TABLE club_booking_field");
        $this->addSql("DROP TABLE club_booking_interval");
    }
}
