<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20110718144652 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("CREATE TABLE club_shop_coupon (id INT AUTO_INCREMENT NOT NULL, coupon_key VARCHAR(255) NOT NULL, value NUMERIC(10, 2) NOT NULL, max_usage INT NOT NULL, expire_at DATETIME NOT NULL, created_at DATETIME NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE club_shop_coupon_log (id INT AUTO_INCREMENT NOT NULL, coupon_id INT DEFAULT NULL, created_at DATETIME NOT NULL, INDEX IDX_288775AD66C5951B (coupon_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE club_shop_coupon_log ADD FOREIGN KEY (coupon_id) REFERENCES club_shop_coupon(id) ON DELETE CASCADE");
        $this->addSql("DROP TABLE club_shop_subscription_location");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE club_shop_coupon_log DROP FOREIGN KEY ");
        $this->addSql("CREATE TABLE club_shop_subscription_location (subscription_id INT NOT NULL, location_id INT NOT NULL, INDEX IDX_2AD5EE3E9A1887DC (subscription_id), INDEX IDX_2AD5EE3E64D218E (location_id), PRIMARY KEY(subscription_id, location_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE club_shop_subscription_location ADD CONSTRAINT club_shop_subscription_location_ibfk_2 FOREIGN KEY (location_id) REFERENCES club_user_location(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE club_shop_subscription_location ADD CONSTRAINT club_shop_subscription_location_ibfk_1 FOREIGN KEY (subscription_id) REFERENCES club_shop_subscription(id) ON DELETE CASCADE");
        $this->addSql("DROP TABLE club_shop_coupon");
        $this->addSql("DROP TABLE club_shop_coupon_log");
    }
}
