<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20110727121138 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_message_message ADD user_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE club_message_message ADD FOREIGN KEY (user_id) REFERENCES club_user_user(id)");
        $this->addSql("CREATE INDEX IDX_392338ADA76ED395 ON club_message_message (user_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_message_message DROP FOREIGN KEY ");
        $this->addSql("DROP INDEX IDX_392338ADA76ED395 ON club_message_message");
        $this->addSql("ALTER TABLE club_message_message DROP user_id");
    }
}
