<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20111114222930 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_shop_subscription_ticket_attribute ADD subscription_ticket_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE club_shop_subscription_ticket_attribute ADD CONSTRAINT FK_F017E15442BF856E FOREIGN KEY (subscription_ticket_id) REFERENCES club_shop_subscription_ticket(id)");
        $this->addSql("CREATE INDEX IDX_F017E15442BF856E ON club_shop_subscription_ticket_attribute (subscription_ticket_id)");
        $this->addSql("ALTER TABLE club_shop_subscription_ticket DROP FOREIGN KEY FK_2DF24DBD44E1E258");
        $this->addSql("DROP INDEX IDX_2DF24DBD44E1E258 ON club_shop_subscription_ticket");
        $this->addSql("ALTER TABLE club_shop_subscription_ticket DROP subscription_ticket_attribute_id");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_shop_subscription_ticket ADD subscription_ticket_attribute_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE club_shop_subscription_ticket ADD CONSTRAINT FK_2DF24DBD44E1E258 FOREIGN KEY (subscription_ticket_attribute_id) REFERENCES club_shop_subscription_ticket_attribute(id)");
        $this->addSql("CREATE INDEX IDX_2DF24DBD44E1E258 ON club_shop_subscription_ticket (subscription_ticket_attribute_id)");
        $this->addSql("ALTER TABLE club_shop_subscription_ticket_attribute DROP FOREIGN KEY FK_F017E15442BF856E");
        $this->addSql("DROP INDEX IDX_F017E15442BF856E ON club_shop_subscription_ticket_attribute");
        $this->addSql("ALTER TABLE club_shop_subscription_ticket_attribute DROP subscription_ticket_id");
    }
}
