<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20111125114245 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE club_booking_booking_user (booking_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_CE8B35863301C60 (booking_id), INDEX IDX_CE8B3586A76ED395 (user_id), PRIMARY KEY(booking_id, user_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE club_booking_booking_user ADD CONSTRAINT FK_CE8B35863301C60 FOREIGN KEY (booking_id) REFERENCES club_booking_booking(id)");
        $this->addSql("ALTER TABLE club_booking_booking_user ADD CONSTRAINT FK_CE8B3586A76ED395 FOREIGN KEY (user_id) REFERENCES club_user_user(id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE club_booking_booking_user");
    }
}
