<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120321115851 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_shop_transaction DROP FOREIGN KEY FK_C1341A2028D09BFE");
        $this->addSql("DROP TABLE club_shop_transaction");
        $this->addSql("DROP TABLE club_shop_transaction_status");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE club_shop_transaction (id INT AUTO_INCREMENT NOT NULL, transaction_status_id INT DEFAULT NULL, transaction_code VARCHAR(255) NOT NULL, transaction_return_value VARCHAR(255) NOT NULL, INDEX IDX_C1341A2028D09BFE (transaction_status_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE club_shop_transaction_status (id INT AUTO_INCREMENT NOT NULL, status_name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE club_shop_transaction ADD CONSTRAINT FK_C1341A2028D09BFE FOREIGN KEY (transaction_status_id) REFERENCES club_shop_transaction_status(id)");
    }
}
