<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20110719144207 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_shop_subscription ADD order_product_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE club_shop_subscription ADD FOREIGN KEY (order_product_id) REFERENCES club_shop_order_product(id)");
        $this->addSql("CREATE INDEX IDX_69CFA546F65E9B0F ON club_shop_subscription (order_product_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_shop_subscription DROP FOREIGN KEY ");
        $this->addSql("DROP INDEX IDX_69CFA546F65E9B0F ON club_shop_subscription");
        $this->addSql("ALTER TABLE club_shop_subscription DROP order_product_id");
    }
}
