<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120221105929 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_team_team DROP FOREIGN KEY FK_BA08F28264D218E");
        $this->addSql("DROP INDEX IDX_BA08F28264D218E ON club_team_team");
        $this->addSql("ALTER TABLE club_team_team DROP location_id");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_team_team ADD location_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE club_team_team ADD CONSTRAINT FK_BA08F28264D218E FOREIGN KEY (location_id) REFERENCES club_user_location(id)");
        $this->addSql("CREATE INDEX IDX_BA08F28264D218E ON club_team_team (location_id)");
    }
}
