<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20111110201552 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE club_team_schedule_instructor (schedule_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_909B132FA40BC2D5 (schedule_id), INDEX IDX_909B132FA76ED395 (user_id), PRIMARY KEY(schedule_id, user_id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE club_team_schedule_user (schedule_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_860A2A86A40BC2D5 (schedule_id), INDEX IDX_860A2A86A76ED395 (user_id), PRIMARY KEY(schedule_id, user_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE club_team_schedule_instructor ADD CONSTRAINT FK_909B132FA40BC2D5 FOREIGN KEY (schedule_id) REFERENCES club_team_schedule(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE club_team_schedule_instructor ADD CONSTRAINT FK_909B132FA76ED395 FOREIGN KEY (user_id) REFERENCES club_user_user(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE club_team_schedule_user ADD CONSTRAINT FK_860A2A86A40BC2D5 FOREIGN KEY (schedule_id) REFERENCES club_team_schedule(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE club_team_schedule_user ADD CONSTRAINT FK_860A2A86A76ED395 FOREIGN KEY (user_id) REFERENCES club_user_user(id) ON DELETE CASCADE");
        $this->addSql("DROP TABLE club_team_team_instructor");
        $this->addSql("DROP TABLE club_team_team_user");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE club_team_team_instructor (schedule_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_956D0B28A40BC2D5 (schedule_id), INDEX IDX_956D0B28A76ED395 (user_id), PRIMARY KEY(schedule_id, user_id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE club_team_team_user (schedule_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_27C68C06A40BC2D5 (schedule_id), INDEX IDX_27C68C06A76ED395 (user_id), PRIMARY KEY(schedule_id, user_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE club_team_team_instructor ADD CONSTRAINT FK_956D0B28A76ED395 FOREIGN KEY (user_id) REFERENCES club_user_user(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE club_team_team_instructor ADD CONSTRAINT FK_956D0B28A40BC2D5 FOREIGN KEY (schedule_id) REFERENCES club_team_schedule(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE club_team_team_user ADD CONSTRAINT FK_27C68C06A76ED395 FOREIGN KEY (user_id) REFERENCES club_user_user(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE club_team_team_user ADD CONSTRAINT FK_27C68C06A40BC2D5 FOREIGN KEY (schedule_id) REFERENCES club_team_schedule(id) ON DELETE CASCADE");
        $this->addSql("DROP TABLE club_team_schedule_instructor");
        $this->addSql("DROP TABLE club_team_schedule_user");
    }
}
