<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20110726131855 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE club_mail_mail_location ADD FOREIGN KEY (mail_id) REFERENCES club_message_message(id)");
        $this->addSql("ALTER TABLE club_mail_mail_group ADD FOREIGN KEY (mail_id) REFERENCES club_message_message(id)");
        $this->addSql("ALTER TABLE club_mail_mail_user ADD FOREIGN KEY (mail_id) REFERENCES club_message_message(id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE club_mail_mail_group DROP FOREIGN KEY ");
        $this->addSql("ALTER TABLE club_mail_mail_location DROP FOREIGN KEY ");
        $this->addSql("ALTER TABLE club_mail_mail_user DROP FOREIGN KEY ");
    }
}
