<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120414192112 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_message_message_recipient ADD user_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE club_message_message_recipient ADD CONSTRAINT FK_A6D53CCBA76ED395 FOREIGN KEY (user_id) REFERENCES club_user_user(id)");
        $this->addSql("CREATE INDEX IDX_A6D53CCBA76ED395 ON club_message_message_recipient (user_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_message_message_recipient DROP FOREIGN KEY FK_A6D53CCBA76ED395");
        $this->addSql("DROP INDEX IDX_A6D53CCBA76ED395 ON club_message_message_recipient");
        $this->addSql("ALTER TABLE club_message_message_recipient DROP user_id");
    }
}
