<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20111016154001 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_account_ledger DROP FOREIGN KEY club_account_ledger_ibfk_1");
        $this->addSql("ALTER TABLE club_shop_product DROP FOREIGN KEY club_shop_product_ibfk_2");
        $this->addSql("ALTER TABLE club_shop_product DROP FOREIGN KEY club_shop_product_ibfk_1");
        $this->addSql("DROP TABLE club_account_account");
        $this->addSql("DROP TABLE club_account_ledger");
        $this->addSql("DROP TABLE club_shop_vat");
        $this->addSql("ALTER TABLE club_shop_cart DROP vat_price");
        $this->addSql("ALTER TABLE club_shop_order_product DROP vat_rate");
        $this->addSql("ALTER TABLE club_shop_product DROP FOREIGN KEY club_shop_product_ibfk_2");
        $this->addSql("ALTER TABLE club_shop_product DROP FOREIGN KEY club_shop_product_ibfk_1");
        $this->addSql("DROP INDEX IDX_AACDEC77B5B63A6B ON club_shop_product");
        $this->addSql("DROP INDEX IDX_AACDEC779B6B5FBA ON club_shop_product");
        $this->addSql("ALTER TABLE club_shop_product DROP account_id, DROP vat_id");
        $this->addSql("ALTER TABLE club_shop_order DROP vat_price");
        $this->addSql("ALTER TABLE club_shop_cart_product DROP vat_rate");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE club_account_account (id INT AUTO_INCREMENT NOT NULL, account_name VARCHAR(255) NOT NULL, account_number VARCHAR(255) NOT NULL, account_type VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_AB0B7032D2B0F9AC (account_name), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE club_account_ledger (id INT AUTO_INCREMENT NOT NULL, account_id INT DEFAULT NULL, user_id INT DEFAULT NULL, order_id INT DEFAULT NULL, value NUMERIC(10, 2) NOT NULL, note VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, INDEX IDX_2BFEDA1C9B6B5FBA (account_id), INDEX IDX_2BFEDA1CA76ED395 (user_id), INDEX IDX_2BFEDA1C8D9F6D38 (order_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE club_shop_vat (id INT AUTO_INCREMENT NOT NULL, vat_name VARCHAR(255) NOT NULL, rate NUMERIC(10, 0) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE club_account_ledger ADD CONSTRAINT club_account_ledger_ibfk_1 FOREIGN KEY (account_id) REFERENCES club_account_account(id)");
        $this->addSql("ALTER TABLE club_account_ledger ADD CONSTRAINT club_account_ledger_ibfk_2 FOREIGN KEY (user_id) REFERENCES club_user_user(id)");
        $this->addSql("ALTER TABLE club_account_ledger ADD CONSTRAINT FK_2BFEDA1C8D9F6D38 FOREIGN KEY (order_id) REFERENCES club_shop_order(id)");
        $this->addSql("ALTER TABLE club_shop_cart ADD vat_price NUMERIC(10, 2) NOT NULL");
        $this->addSql("ALTER TABLE club_shop_cart_product ADD vat_rate NUMERIC(10, 2) NOT NULL");
        $this->addSql("ALTER TABLE club_shop_order ADD vat_price NUMERIC(10, 2) NOT NULL");
        $this->addSql("ALTER TABLE club_shop_order_product ADD vat_rate NUMERIC(10, 2) NOT NULL");
        $this->addSql("ALTER TABLE club_shop_product ADD account_id INT DEFAULT NULL, ADD vat_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE club_shop_product ADD CONSTRAINT club_shop_product_ibfk_2 FOREIGN KEY (account_id) REFERENCES club_account_account(id)");
        $this->addSql("ALTER TABLE club_shop_product ADD CONSTRAINT club_shop_product_ibfk_1 FOREIGN KEY (vat_id) REFERENCES club_shop_vat(id)");
        $this->addSql("CREATE INDEX IDX_AACDEC77B5B63A6B ON club_shop_product (vat_id)");
        $this->addSql("CREATE INDEX IDX_AACDEC779B6B5FBA ON club_shop_product (account_id)");
    }
}
