<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120131150242 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_booking_booking ADD field_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE club_booking_booking ADD CONSTRAINT FK_A5A49A20443707B0 FOREIGN KEY (field_id) REFERENCES club_booking_field(id)");
        $this->addSql("CREATE INDEX IDX_A5A49A20443707B0 ON club_booking_booking (field_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_booking_booking DROP FOREIGN KEY FK_A5A49A20443707B0");
        $this->addSql("DROP INDEX IDX_A5A49A20443707B0 ON club_booking_booking");
        $this->addSql("ALTER TABLE club_booking_booking DROP field_id");
    }
}
