<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120130133151 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_user_currency DROP symbol_left, DROP symbol_right, DROP decimal_places, DROP value, DROP active");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_user_currency ADD symbol_left VARCHAR(255) DEFAULT NULL, ADD symbol_right VARCHAR(255) DEFAULT NULL, ADD decimal_places VARCHAR(255) NOT NULL, ADD value NUMERIC(10, 5) NOT NULL, ADD active TINYINT(1) NOT NULL");
    }
}
