<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20111010181020 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE club_shop_subscription_location (subscription_id INT NOT NULL, location_id INT NOT NULL, INDEX IDX_2AD5EE3E9A1887DC (subscription_id), INDEX IDX_2AD5EE3E64D218E (location_id), PRIMARY KEY(subscription_id, location_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE club_shop_subscription_location ADD CONSTRAINT FK_2AD5EE3E9A1887DC FOREIGN KEY (subscription_id) REFERENCES club_shop_subscription(id)");
        $this->addSql("ALTER TABLE club_shop_subscription_location ADD CONSTRAINT FK_2AD5EE3E64D218E FOREIGN KEY (location_id) REFERENCES club_user_location(id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE club_shop_subscription_location");
    }
}
