<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20110719152501 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_shop_order_product CHANGE vat vat_rate NUMERIC(10, 0) NOT NULL");
        $this->addSql("ALTER TABLE club_shop_cart_product ADD vat_rate NUMERIC(10, 2) NOT NULL, DROP vat");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_shop_cart_product ADD vat NUMERIC(10, 0) NOT NULL, DROP vat_rate");
        $this->addSql("ALTER TABLE club_shop_order_product CHANGE vat_rate vat NUMERIC(10, 0) NOT NULL");
    }
}
