<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120417095603 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_match_match DROP FOREIGN KEY FK_1AC3E22F5DFCD4B8");
        $this->addSql("ALTER TABLE club_match_match ADD CONSTRAINT FK_1AC3E22F5DFCD4B8 FOREIGN KEY (winner_id) REFERENCES club_match_match_team(id) ON DELETE CASCADE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_match_match DROP FOREIGN KEY FK_1AC3E22F5DFCD4B8");
        $this->addSql("ALTER TABLE club_match_match ADD CONSTRAINT FK_1AC3E22F5DFCD4B8 FOREIGN KEY (winner_id) REFERENCES club_match_match_team(id)");
    }
}
