<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120314164550 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_message_message_attachment DROP FOREIGN KEY FK_7A27EA70537A1329");
        $this->addSql("ALTER TABLE club_message_message_attachment ADD CONSTRAINT FK_7A27EA70537A1329 FOREIGN KEY (message_id) REFERENCES club_message_message(id) ON DELETE CASCADE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_message_message_attachment DROP FOREIGN KEY FK_7A27EA70537A1329");
        $this->addSql("ALTER TABLE club_message_message_attachment ADD CONSTRAINT FK_7A27EA70537A1329 FOREIGN KEY (message_id) REFERENCES club_message_message(id)");
    }
}
