<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120406224827 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_booking_plan DROP FOREIGN KEY FK_BF7FD1C3E6FF4589");
        $this->addSql("ALTER TABLE club_booking_plan ADD CONSTRAINT FK_BF7FD1C3E6FF4589 FOREIGN KEY (plan_category_id) REFERENCES club_booking_plan_category(id) ON DELETE CASCADE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_booking_plan DROP FOREIGN KEY FK_BF7FD1C3E6FF4589");
        $this->addSql("ALTER TABLE club_booking_plan ADD CONSTRAINT FK_BF7FD1C3E6FF4589 FOREIGN KEY (plan_category_id) REFERENCES club_booking_plan_category(id)");
    }
}
