<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20111107112824 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("CREATE TABLE club_team_repetition (id INT AUTO_INCREMENT NOT NULL, team_id INT DEFAULT NULL, first_date DATETIME NOT NULL, last_date DATETIME NOT NULL, day_period INT NOT NULL, day_of_month INT NOT NULL, day_of_week INT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_BC76ED49296CD8AE (team_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE club_team_repetition ADD CONSTRAINT FK_BC76ED49296CD8AE FOREIGN KEY (team_id) REFERENCES club_team_team(id)");
        $this->addSql("DROP TABLE Repetition");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("CREATE TABLE Repetition (id INT AUTO_INCREMENT NOT NULL, team_id INT DEFAULT NULL, first_date DATETIME NOT NULL, last_date DATETIME NOT NULL, day_period INT NOT NULL, day_of_month INT NOT NULL, day_of_week INT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_D2E4AE82296CD8AE (team_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE Repetition ADD CONSTRAINT FK_D2E4AE82296CD8AE FOREIGN KEY (team_id) REFERENCES club_team_team(id)");
        $this->addSql("DROP TABLE club_team_repetition");
    }
}
