<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120313080007 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("DROP INDEX IDX_3D42B7FF92F3E70 ON club_user_location");
        $this->addSql("ALTER TABLE club_user_location ADD country VARCHAR(255) NOT NULL, DROP country_id");
        $this->addSql("ALTER TABLE club_user_profile_address CHANGE country country VARCHAR(255) NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE club_user_location ADD country_id INT DEFAULT NULL, DROP country");
        $this->addSql("CREATE INDEX IDX_3D42B7FF92F3E70 ON club_user_location (country_id)");
        $this->addSql("ALTER TABLE club_user_profile_address CHANGE country country VARCHAR(255) DEFAULT NULL");
    }
}
