<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120208183119 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_user_location ADD country_id INT DEFAULT NULL, ADD street LONGTEXT DEFAULT NULL, ADD postal_code VARCHAR(255) DEFAULT NULL, ADD city VARCHAR(255) DEFAULT NULL, ADD state VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE club_user_location ADD CONSTRAINT FK_3D42B7FF92F3E70 FOREIGN KEY (country_id) REFERENCES club_user_country(id)");
        $this->addSql("CREATE INDEX IDX_3D42B7FF92F3E70 ON club_user_location (country_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_user_location DROP FOREIGN KEY FK_3D42B7FF92F3E70");
        $this->addSql("DROP INDEX IDX_3D42B7FF92F3E70 ON club_user_location");
        $this->addSql("ALTER TABLE club_user_location DROP country_id, DROP street, DROP postal_code, DROP city, DROP state");
    }
}
