<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20110707161439 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE club_shop_product ADD account_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE club_shop_product ADD FOREIGN KEY (account_id) REFERENCES club_account_account(id)");
        $this->addSql("CREATE INDEX IDX_AACDEC779B6B5FBA ON club_shop_product (account_id)");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_AB0B7032D2B0F9AC ON club_account_account (account_name)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("DROP INDEX UNIQ_AB0B7032D2B0F9AC ON club_account_account");
        $this->addSql("ALTER TABLE club_shop_product DROP FOREIGN KEY ");
        $this->addSql("DROP INDEX IDX_AACDEC779B6B5FBA ON club_shop_product");
        $this->addSql("ALTER TABLE club_shop_product DROP account_id");
    }
}
