<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20111116155424 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_team_schedule DROP FOREIGN KEY FK_5FBD8B31296CD8AE");
        $this->addSql("ALTER TABLE club_team_schedule ADD CONSTRAINT FK_5FBD8B31296CD8AE FOREIGN KEY (team_id) REFERENCES club_team_team(id) ON DELETE CASCADE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_team_schedule DROP FOREIGN KEY FK_5FBD8B31296CD8AE");
        $this->addSql("ALTER TABLE club_team_schedule ADD CONSTRAINT FK_5FBD8B31296CD8AE FOREIGN KEY (team_id) REFERENCES club_team_team(id)");
    }
}
