<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20111209154641 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE club_team_schedule_user DROP PRIMARY KEY");
        $this->addSql("ALTER TABLE club_team_schedule_user ADD id INT AUTO_INCREMENT NOT NULL PRIMARY KEY, ADD created_at DATETIME NOT NULL, CHANGE schedule_id schedule_id INT DEFAULT NULL, CHANGE user_id user_id INT DEFAULT NULL");
        #$this->addSql("ALTER TABLE club_team_schedule_user ADD CONSTRAINT FK_860A2A86A76ED395 FOREIGN KEY (user_id) REFERENCES club_user_user(id)");
        #$this->addSql("ALTER TABLE club_team_schedule_user ADD CONSTRAINT FK_860A2A86A40BC2D5 FOREIGN KEY (schedule_id) REFERENCES club_team_schedule(id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE club_team_schedule_user DROP FOREIGN KEY FK_860A2A86A76ED395");
        $this->addSql("ALTER TABLE club_team_schedule_user DROP FOREIGN KEY FK_860A2A86A40BC2D5");
        $this->addSql("ALTER TABLE club_team_schedule_user DROP PRIMARY KEY");
        $this->addSql("ALTER TABLE club_team_schedule_user DROP id, DROP created_at, CHANGE user_id user_id INT NOT NULL, CHANGE schedule_id schedule_id INT NOT NULL");
    }
}
