<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20111016115408 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_account_ledger ADD order_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE club_account_ledger ADD CONSTRAINT FK_2BFEDA1C8D9F6D38 FOREIGN KEY (order_id) REFERENCES club_shop_order(id)");
        $this->addSql("CREATE INDEX IDX_2BFEDA1C8D9F6D38 ON club_account_ledger (order_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_account_ledger DROP FOREIGN KEY FK_2BFEDA1C8D9F6D38");
        $this->addSql("DROP INDEX IDX_2BFEDA1C8D9F6D38 ON club_account_ledger");
        $this->addSql("ALTER TABLE club_account_ledger DROP order_id");
    }
}
