<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120221091947 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_team_schedule DROP FOREIGN KEY FK_5FBD8B31296CD8AE");
        $this->addSql("CREATE TABLE club_team_team_category (id INT AUTO_INCREMENT NOT NULL, team_name VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, penalty NUMERIC(10, 2) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("DROP TABLE club_team_team");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_team_schedule DROP FOREIGN KEY FK_5FBD8B31296CD8AE");
        $this->addSql("CREATE TABLE club_team_team (id INT AUTO_INCREMENT NOT NULL, team_name VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, penalty NUMERIC(10, 2) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("DROP TABLE club_team_team_category");
    }
}
