<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120417095759 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_match_match_comment DROP FOREIGN KEY FK_E97997EC2ABEACD6");
        $this->addSql("ALTER TABLE club_match_match_comment ADD CONSTRAINT FK_E97997EC2ABEACD6 FOREIGN KEY (match_id) REFERENCES club_match_match(id) ON DELETE CASCADE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_match_match_comment DROP FOREIGN KEY FK_E97997EC2ABEACD6");
        $this->addSql("ALTER TABLE club_match_match_comment ADD CONSTRAINT FK_E97997EC2ABEACD6 FOREIGN KEY (match_id) REFERENCES club_match_match(id)");
    }
}
