<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120416110229 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE club_ranking_match_team ADD team_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE club_ranking_match_team ADD CONSTRAINT FK_6349B806296CD8AE FOREIGN KEY (team_id) REFERENCES club_ranking_team(id) ON DELETE CASCADE");
        $this->addSql("CREATE INDEX IDX_6349B806296CD8AE ON club_ranking_match_team (team_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE club_ranking_match_team DROP FOREIGN KEY FK_6349B806296CD8AE");
        $this->addSql("DROP INDEX IDX_6349B806296CD8AE ON club_ranking_match_team");
        $this->addSql("ALTER TABLE club_ranking_match_team DROP team_id");
    }
}
