<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120414190145 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE club_message_message_recipient (id INT AUTO_INCREMENT NOT NULL, message_id INT DEFAULT NULL, recipient VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, INDEX IDX_A6D53CCB537A1329 (message_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE club_message_message_recipient ADD CONSTRAINT FK_A6D53CCB537A1329 FOREIGN KEY (message_id) REFERENCES club_message_message(id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE club_message_message_recipient");
    }
}
