<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20110726110422 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("DROP TABLE location_mail");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("CREATE TABLE location_mail (location_id INT NOT NULL, mail_id INT NOT NULL, INDEX IDX_D122190864D218E (location_id), INDEX IDX_D1221908C8776F01 (mail_id), PRIMARY KEY(location_id, mail_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE location_mail ADD CONSTRAINT location_mail_ibfk_2 FOREIGN KEY (mail_id) REFERENCES club_mail(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE location_mail ADD CONSTRAINT location_mail_ibfk_1 FOREIGN KEY (location_id) REFERENCES club_user_location(id) ON DELETE CASCADE");
    }
}
