<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120212110803 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_user_filter_attribute DROP FOREIGN KEY FK_C0591B7CB6E62EFA");
        $this->addSql("DROP TABLE club_user_attribute");
        $this->addSql("ALTER TABLE club_user_filter_attribute DROP FOREIGN KEY FK_C0591B7CB6E62EFA");
        $this->addSql("DROP INDEX IDX_C0591B7CB6E62EFA ON club_user_filter_attribute");
        $this->addSql("ALTER TABLE club_user_filter_attribute ADD attribute VARCHAR(255) NOT NULL, DROP attribute_id");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE club_user_attribute (id INT AUTO_INCREMENT NOT NULL, attribute_name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE club_user_filter_attribute ADD attribute_id INT DEFAULT NULL, DROP attribute");
        $this->addSql("ALTER TABLE club_user_filter_attribute ADD CONSTRAINT FK_C0591B7CB6E62EFA FOREIGN KEY (attribute_id) REFERENCES club_user_attribute(id)");
        $this->addSql("CREATE INDEX IDX_C0591B7CB6E62EFA ON club_user_filter_attribute (attribute_id)");
    }
}
