<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20111128155554 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE club_team_schedule_field (schedule_id INT NOT NULL, field_id INT NOT NULL, INDEX IDX_50250385A40BC2D5 (schedule_id), INDEX IDX_50250385443707B0 (field_id), PRIMARY KEY(schedule_id, field_id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE club_team_schedule_field ADD CONSTRAINT FK_50250385A40BC2D5 FOREIGN KEY (schedule_id) REFERENCES club_team_schedule(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE club_team_schedule_field ADD CONSTRAINT FK_50250385443707B0 FOREIGN KEY (field_id) REFERENCES club_booking_field(id) ON DELETE CASCADE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE club_team_schedule_field");
    }
}
