<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120306175114 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_ranking_match ADD winner_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE club_ranking_match ADD CONSTRAINT FK_CA58D4005DFCD4B8 FOREIGN KEY (winner_id) REFERENCES club_ranking_match_team(id)");
        $this->addSql("CREATE INDEX IDX_CA58D4005DFCD4B8 ON club_ranking_match (winner_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE club_ranking_match DROP FOREIGN KEY FK_CA58D4005DFCD4B8");
        $this->addSql("DROP INDEX IDX_CA58D4005DFCD4B8 ON club_ranking_match");
        $this->addSql("ALTER TABLE club_ranking_match DROP winner_id");
    }
}
