<?php

namespace Club\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Country
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Country extends EntityRepository
{
}
