<?php

namespace Club\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Filter
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Filter extends EntityRepository
{
  public function findActive(\Club\UserBundle\Entity\User $user)
  {
    $filter = $this->_em->getRepository('ClubUserBundle:Filter')->findOneBy(array(
      'user' => $user->getId(),
      'active' => 1
    ));

    if (!$filter) {
      $filter = $this->createFilter($user);
      $filter->setActive(1);

      $this->_em->flush();
    }

    return $filter;
  }

  public function activateFilter(\Club\UserBundle\Entity\User $user, \Club\UserBundle\Entity\Filter $filter)
  {
    $old_filter = $this->findActive($user);
    $old_filter->setActive(0);

    $this->_em->persist($old_filter);

    $filter->setActive(1);
    $this->_em->persist($filter);
  }

  public function createFilter(\Club\UserBundle\Entity\User $user)
  {
    $filter = new \Club\UserBundle\Entity\Filter;
    $filter->setFilterName('Working');
    $filter->setActive(0);
    $filter->setUser($user);

    $attributes = $this->_em->getRepository('ClubUserBundle:Attribute')->findAll();

    foreach ($attributes as $attr) {
      $filter_attr = new \Club\UserBundle\Entity\FilterAttribute();
      $filter_attr->setFilter($filter);
      $filter_attr->setAttribute($attr);
      $filter->addAttributes($filter_attr);

      $this->_em->persist($filter_attr);
    }

    $this->_em->persist($filter);

    return $filter;
  }
}
