<?php

namespace Club\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Filter
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Filter extends EntityRepository
{
  public function findActive(\Club\UserBundle\Entity\User $user)
  {
    return $this->_em->getRepository('ClubUserBundle:Filter')->findOneBy(array(
      'user' => $user->getId(),
      'is_active' => 1
    ));
  }
}
