<?php

namespace Club\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LocationConfig
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationConfig extends EntityRepository
{
  public function getByKey(\Club\UserBundle\Entity\Location $location, $key)
  {
    $config = $this->_em->createQueryBuilder()
      ->select('lc')
      ->from('ClubUserBundle:LocationConfig','lc')
      ->leftJoin('lc.config','c')
      ->where('lc.location = :location')
      ->andWhere('c.config_key = :key')
      ->setParameter('key',$key)
      ->setParameter('location',$location->getId())
      ->getQuery()
      ->getSingleResult();

    var_dump($config);
    if (!$config) {
      $config = $this->getByKey($location->getLocation(),$key);
      var_dump($config);
    }

    die('meh');

  }
}
