<?php

namespace Club\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Location
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Location extends EntityRepository
{
  public function getDefault()
  {
    $query = $this->_em->createQueryBuilder()
      ->select('l')
      ->from('ClubUserBundle:Location','l')
      ->orderBy('l.id')
      ->setMaxResults(1)
      ->getQuery();

    return $query->getSingleResult();
  }

  public function getByIds($ids)
  {
    return $this->_em->createQueryBuilder()
      ->select('l')
      ->from('ClubUserBundle:Location','l')
      ->where('l.id IN (:ids)')
      ->setParameter('ids',$ids)
      ->getQuery()
      ->getResult();
  }
}
