<?php

namespace Club\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Location
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Location extends EntityRepository
{
  public function getByIds($ids)
  {
    return $this->_em->createQueryBuilder()
      ->select('l')
      ->from('ClubUserBundle:Location','l')
      ->where('l.id IN (:ids)')
      ->setParameter('ids',$ids)
      ->getQuery()
      ->getResult();
  }

  public function findAllVisible()
  {
    return $this->_em->createQueryBuilder()
      ->select('l')
      ->from('ClubUserBundle:Location','l')
      ->where('l.location IS NOT NULL')
      ->getQuery()
      ->getResult();
  }

  public function getChilds(\Club\UserBundle\Entity\Location $location)
  {
    return $this->_em->createQueryBuilder()
      ->select('l')
      ->from('ClubUserBundle:Location','l')
      ->where('l.location = :parent')
      ->setParameter('parent', $location->getId())
      ->getQuery()
      ->getResult();
  }

  public function getWithChilds(\Club\UserBundle\Entity\Location $location)
  {
    $location->childs = $this->getChilds($location);

    foreach ($location->childs as $child) {
      $child->childs = $this->getChilds($child);

      foreach ($child->childs as $child2) {
        $child2->childs = $this->getChilds($child2);
      }
    }

    return $location;
  }
}
