<?php

namespace Club\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Role
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Role extends EntityRepository
{
}
