<?php

namespace Club\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * User
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class User extends EntityRepository
{
  public function findAllActive()
  {
    $dql =
      "SELECT u,s ".
      "FROM Club\UserBundle\Entity\User u ".
      "JOIN u.subscriptions s ".
      "WHERE s.start_date <= :start AND s.expire_date <= :expire";

    $query = $this->_em->createQuery($dql);
    $query->setParameters(array(
      'start' => date('Y-m-d'),
      'expire' => date('Y-m-d')
    ));

    return $query->getResult();
  }

  public function findNextMemberNumber()
  {
    $dql = "SELECT u FROM Club\UserBundle\Entity\User u ORDER BY u.member_number DESC";

    $query = $this->_em->createQuery($dql);
    $query->setMaxResults(1);

    $r = $query->getResult();

    if (!count($r)) return 1;
    return $r[0]->getMemberNumber()+1;
  }

  public function getUsers($filter)
  {
    $dql = "SELECT u FROM Club\UserBundle\Entity\User u LEFT JOIN u.profile p WHERE (CONCAT(p.first_name,p.last_name) LIKE ?1 OR u.member_number = ?2)";

    $users = $this->_em->createQuery($dql)
      ->setParameter(1,'%'.preg_replace("/\s/","",$filter->getMemberNumber().'%'))
      ->setParameter(2,$filter->getMemberNumber())
      ->getResult();

    return $users;
  }
}
