<?php

namespace Club\ExchangeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExchangeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExchangeRepository extends EntityRepository
{
    public function getComing()
    {
        return $this->_em->createQueryBuilder()
            ->select('r')
            ->from('ClubExchangeBundle:Exchange', 'r')
            ->where('r.play_time > :date')
            ->andWhere('r.closed = false')
            ->orderBy('r.play_time')
            ->setParameter('date', new \DateTime())
            ->getQuery()
            ->getResult();
    }

    public function getUsers(\Club\ExchangeBundle\Entity\Exchange $exchange)
    {
        $users = array(
            $exchange->getUser()->getId() => $exchange->getUser()
        );

        foreach ($exchange->getExchangeComments() as $comment) {
            $users[$comment->getUser()->getId()] = $comment->getUser();
        }

        return $users;
    }
}
