<?php

namespace Club\ExchangeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExchangeCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExchangeCommentRepository extends EntityRepository
{
}
