<?php

namespace Club\PasskeyBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PasskeyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PasskeyRepository extends EntityRepository
{
}