<?php

namespace Club\TaskBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Task
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Task extends EntityRepository
{
}
