<?php

namespace Club\TaskBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Task
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Task extends EntityRepository
{
  public function getTasksToExecute()
  {
    $tasks = $this->_em->createQueryBuilder()
      ->select('t')
      ->from('\Club\TaskBundle\Entity\Task','t')
      ->where('t.next_run_at < ?1')
      ->setParameter(1,date('Y-m-d H:i:s'))
      ->getQuery()
      ->getResult();

    return $tasks;
  }
}
