<?php

namespace Club\EventBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Attend
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Attend extends EntityRepository
{
}
