<?php

namespace Club\WelcomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogRepository extends EntityRepository
{
    public function getPaginator($results, $page)
    {
        $offset = ($page < 1) ? 1 : ($page-1)*$results;

        $dql = "SELECT b FROM Club\WelcomeBundle\Entity\Blog b ORDER BY b.id DESC";
        $query = $this->_em->createQuery($dql)
            ->setFirstResult($offset)
            ->setMaxResults($results);

        return new \Doctrine\ORM\Tools\Pagination\Paginator($query, false);
    }
}
