<?php

namespace Club\WelcomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WelcomeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WelcomeRepository extends EntityRepository
{
}
