<?php

namespace Club\LogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Log
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Log extends EntityRepository
{
}
