<?php

namespace Club\ShopBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Category
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Category extends EntityRepository
{
}