<?php

namespace Club\ShopBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Module
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Module extends EntityRepository
{
}