<?php

namespace Club\ShopBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OrderStatus
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderStatus extends EntityRepository
{
  public function getDefaultStatus()
  {
    $query = $this->_em->createQueryBuilder()
      ->select('s')
      ->from('\Club\ShopBundle\Entity\OrderStatus')
      ->orderBy('s.priority')
      ->getQuery();

    echo $query;
    die();
  }
}
