<?php

namespace Club\ShopBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Product
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Product extends EntityRepository
{
  public function findByCategories($categories)
  {
    $dql = 'SELECT p FROM Club\ShopBundle\Entity\Product p JOIN p.categories c WHERE c.id IN ('.join(",", $categories).')';

    return $this->_em->createQuery($dql)->getResult();
  }

  public function getAccount(\Club\ShopBundle\Entity\Product $product, \Club\UserBundle\Entity\User $user)
  {
    if ($product->getAccount())
      return $product->getAccount();

    $account = $this->_em->getRepository('ClubUserBundle:LocationConfig')->getObjectByKey(
      'account_default_income',
      $user->getLocation()
    );

    return $account;

  }
}
