<?php

namespace Club\ShopBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Special
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Special extends EntityRepository
{
}