<?php

namespace Club\ShopBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Subscription
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Subscription extends EntityRepository
{
  public function getActivePause($subscription)
  {
    $pause = $this->_em->createQueryBuilder()
      ->select('sp')
      ->from('ClubShopBundle:SubscriptionPause','sp')
      ->where('sp.subscription = ?1')
      ->andWhere('sp.expire_date IS NULL')
      ->setParameter(1, $subscription->getId())
      ->getQuery()
      ->getSingleResult();

    return $pause;
  }

  public function getExpiredAutoRenewalSubscriptions()
  {
    return $this->_em->createQueryBuilder()
      ->select('s')
      ->from('ClubShopBundle:Subscription','s')
      ->andWhere('s.expire_date >= :expire_date')
      ->setParameter('expire_date',date('Y-m-d'))
      ->getQuery()
      ->getResult();
  }

  public function getAttributeForSubscription(\Club\ShopBundle\Entity\Subscription $subscription,$attribute_name)
  {
    return $this->getAttributeQuery($subscription, $attribute_name)
      ->getQuery()
      ->getSingleResult();
  }

  public function getAllowedPauses(\Club\ShopBundle\Entity\Subscription $subscription)
  {
    $res = $this->getAttributeQuery($subscription, 'AllowedPauses')
      ->getQuery()
      ->getResult();

    if (!count($res))
      return 0;

    return $res[0]->getValue();
  }

  public function getTicketsLeft(\Club\ShopBundle\Entity\Subscription $subscription)
  {
    $used = $this->getUsedTickets($subscription);

    $res = $this->getAttributeQuery($subscription, 'Ticket')
      ->getQuery()
      ->getResult();

    if (!count($res))
      return 0;

    return $res[0]->getValue()-$used;
  }

  private function getUsedTickets(\Club\ShopBundle\Entity\Subscription $subscription)
  {
    $tickets = $this->_em->createQueryBuilder()
      ->select('SUM(st.tickets)')
      ->from('ClubShopBundle:SubscriptionTicket','st')
      ->where('st.subscription = ?1')
      ->setParameter(1, $subscription->getId())
      ->getQuery()
      ->getSingleScalarResult();

    if (!$tickets)
      return 0;

    return $tickets;
  }

  private function getAttributeQuery(\Club\ShopBundle\Entity\Subscription $subscription, $attribute_name)
  {
    return $this->_em->createQueryBuilder()
      ->select('sa')
      ->from('ClubShopBundle:SubscriptionAttribute','sa')
      ->where('sa.subscription = :subscription')
      ->andWhere('sa.attribute_name = :attribute')
      ->setParameter('subscription', $subscription->getId())
      ->setParameter('attribute', $attribute_name);
  }
}
