<?php

namespace Club\ShopBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Transaction
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Transaction extends EntityRepository
{
}