<?php

namespace Club\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConnectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConnectionRepository extends EntityRepository
{
    public function getDistinct(\Club\UserBundle\Entity\User $user)
    {
        $q = $this->createQueryBuilder('c')
            ->where('c.user = :user')
            ->groupBy('c.connection')
            ->setParameter('user', $user->getId())
            ->getQuery()
            ->getResult();

        return $q;
    }
}
