<?php

namespace Club\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationRepository extends EntityRepository
{
  public function getByIds($ids)
  {
    return $this->_em->createQueryBuilder()
      ->select('l')
      ->from('ClubUserBundle:Location','l')
      ->where('l.id IN (:ids)')
      ->setParameter('ids',$ids)
      ->getQuery()
      ->getResult();
  }

  public function findAllVisible()
  {
    return $this->_em->createQueryBuilder()
      ->select('l')
      ->from('ClubUserBundle:Location','l')
      ->where('l.location IS NOT NULL')
      ->getQuery()
      ->getResult();
  }
}
