<?php

namespace Club\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserSettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserSettingRepository extends EntityRepository
{
  public function getUserArray(\Club\UserBundle\Entity\User $user)
  {
    $settings = $this->_em->getRepository('ClubUserBundle:UserSetting')->findBy(array(
      'user' => $user->getId()
    ));

    $res = array();
    foreach ($settings as $setting) {
      $res[$setting->getAttribute()] = $setting->getValue();
    }

    return $res;
  }
}
