<?php

namespace Club\ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CartProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartProductRepository extends EntityRepository
{
    public function getProductInCart(\Club\ShopBundle\Entity\Product $product, \Club\ShopBundle\Entity\Cart $cart)
    {
        return $this->createQueryBuilder('cp')
            ->join('cp.cart', 'c')
            ->join('cp.product', 'p')
            ->where('c.id = :cart')
            ->andWhere('p.id = :product')
            ->setParameter('cart', $cart->getId())
            ->setParameter('product', $product->getId())
            ->getQuery()
            ->getOneOrNullResult();
    }
}
