<?php

namespace Club\ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function getRoot(\Club\UserBundle\Entity\Location $location)
    {
        return $this->createQueryBuilder('c')
            ->where('c.location = :location')
            ->andWhere('c.category IS NULL')
            ->setParameter('location', $location->getId())
            ->getQuery()
            ->getResult();
    }
}
