<?php

namespace Club\ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CouponRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CouponRepository extends EntityRepository
{
  public function getCoupon($coupon_key)
  {
    $coupon = $this->_em->createQueryBuilder()
      ->select('c')
      ->from('ClubShopBundle:Coupon','c')
      ->where('c.coupon_key = :coupon')
      ->andWhere('c.expire_at >= :expire')
      ->setParameter('coupon', $coupon_key)
      ->setParameter('expire', date('Y-m-d H:i:s'))
      ->getQuery()
      ->getOneOrNullResult();

    return $coupon;
  }
}
