<?php

namespace Club\ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrderStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderStatusRepository extends EntityRepository
{
  public function getDefaultStatus()
  {
    return $this->_em->createQueryBuilder()
      ->select('s')
      ->from('ClubShopBundle:OrderStatus','s')
      ->where('s.cancelled = false')
      ->andWhere('s.accepted = false')
      ->orderBy('s.priority')
      ->setMaxResults(1)
      ->getQuery()
      ->getSingleResult();
  }

  public function getAcceptedStatus()
  {
    return $this->_em->createQueryBuilder()
      ->select('s')
      ->from('ClubShopBundle:OrderStatus','s')
      ->where('s.accepted = 1')
      ->setMaxResults(1)
      ->getQuery()
      ->getSingleResult();
  }

  public function getCancelledStatus()
  {
    return $this->_em->createQueryBuilder()
      ->select('s')
      ->from('ClubShopBundle:OrderStatus','s')
      ->where('s.cancelled = 1')
      ->setMaxResults(1)
      ->getQuery()
      ->getSingleResult();
  }

}
