<?php

namespace Club\ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function getByCategory(\Club\ShopBundle\Entity\Category $category, $limit=10)
    {
        return $this->createQueryBuilder('p')
            ->join('p.categories', 'c')
            ->where('c.id = :category')
            ->orderBy('p.priority', 'DESC')
            ->setMaxResults($limit)
            ->setParameter('category', $category)
            ->getQuery()
            ->getResult();
    }
}
