<?php

namespace Club\ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SubscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriptionRepository extends EntityRepository
{
  public function getActivePause($subscription)
  {
    $pause = $this->_em->createQueryBuilder()
      ->select('sp')
      ->from('ClubShopBundle:SubscriptionPause','sp')
      ->where('sp.subscription = ?1')
      ->andWhere('sp.expire_date IS NULL')
      ->setParameter(1, $subscription->getId())
      ->getQuery()
      ->getSingleResult();

    return $pause;
  }

  public function getExpiredSubscriptions()
  {
    return $this->_em->createQueryBuilder()
      ->select('s')
      ->from('ClubShopBundle:Subscription','s')
      ->where('s.expire_date <= :expire_date')
      ->andWhere('s.expire_date IS NOT NULL')
      ->setParameter('expire_date',date('Y-m-d H:i:s'))
      ->getQuery()
      ->getResult();
  }

  public function getActiveTicketSubscriptions()
  {
    return $this->_em->createQueryBuilder()
      ->select('s')
      ->from('ClubShopBundle:Subscription','s')
      ->where('s.type = :type')
      ->setParameter('type','ticket')
      ->getQuery()
      ->getResult();
  }

  public function getSingleActiveSubscriptionForTeam(\Club\UserBundle\Entity\User $user)
  {
    $subscriptions = $this->_em->createQueryBuilder()
      ->select('s')
      ->from('ClubShopBundle:Subscription','s')
      ->where('s.user = :user')
      ->andWhere('(s.expire_date > :date OR s.expire_date IS NULL)')
      ->orderBy('s.type, s.expire_date')
      ->setParameter('date', date('Y-m-d H:i:s'))
      ->setParameter('user', $user->getId())
      ->getQuery()
      ->getResult();

    foreach ($subscriptions as $sub) {
      if ($sub->hasAttribute('team'))
        return $sub;
    }

    return false;
  }

  public function getEmptyTicketAutoRenewalSubscriptions()
  {
    $res = array();
    foreach ($this->getActiveTicketSubscriptions() as $subscription) {
      if (!$this->getTicketsLeft($subscription) && $this->isAutoRenewal($subscription))
        $res[] = $subscription;
    }

    return $res;
  }

  public function isAutoRenewal(\Club\ShopBundle\Entity\Subscription $subscription)
  {
    $attr = $this->getAttributeQuery($subscription, 'auto_renewal')
      ->getQuery()
      ->getResult();

    if ($attr)
      return true;

    return false;
  }

  public function getAttributeForSubscription(\Club\ShopBundle\Entity\Subscription $subscription, $attribute_name)
  {
    $res = $this->getAttributeQuery($subscription, $attribute_name)
      ->getQuery()
      ->getResult();

    if (!count($res))
      return false;

    return $res[0];
  }

  public function getAllowedPauses(\Club\ShopBundle\Entity\Subscription $subscription)
  {
    $res = $this->getAttributeQuery($subscription, 'allowed_pauses')
      ->getQuery()
      ->getResult();

    if (!count($res))
      return 0;

    return $res[0]->getValue();
  }

  public function getTicketsLeft(\Club\ShopBundle\Entity\Subscription $subscription)
  {
    $used = $this->getUsedTickets($subscription);

    $res = $this->getAttributeQuery($subscription, 'ticket')
      ->getQuery()
      ->getResult();

    if (!count($res))
      return 0;

    return $res[0]->getValue()-$used;
  }

  private function getUsedTickets(\Club\ShopBundle\Entity\Subscription $subscription)
  {
    $tickets = $this->_em->createQueryBuilder()
      ->select('SUM(st.tickets)')
      ->from('ClubShopBundle:SubscriptionTicket','st')
      ->where('st.subscription = ?1')
      ->setParameter(1, $subscription->getId())
      ->getQuery()
      ->getSingleScalarResult();

    if (!$tickets)
      return 0;

    return $tickets;
  }

  private function getAttributeQuery(\Club\ShopBundle\Entity\Subscription $subscription, $attribute_name)
  {
    return $this->_em->createQueryBuilder()
      ->select('sa')
      ->from('ClubShopBundle:SubscriptionAttribute','sa')
      ->where('sa.subscription = :subscription')
      ->andWhere('sa.attribute_name = :attribute')
      ->setParameter('subscription', $subscription->getId())
      ->setParameter('attribute', $attribute_name);
  }
}
